### ISSUE TITLE
Integration von Rollladen

### ISSUE THREAD

**Issue by misc2000** [snowdd1/homebridge-knx-de#10]
Hallo,
ich habe KNX im kompletten Haus und versuche gerade nach dem Licht und Fensterkontakte und Heizung seit Wochen stabil funktionieren auch die Rollladen zu integrieren.
Ich habe bei einem ABB JRA Aktor folgende Kommunikationsobjekte folgenden GA zugeordnet:

GA:4/1/0: Buero Roll Auf/Ab      = Behang Auf/ab (1Bit)  (für KNX Taster benutzt)
GA:4/1/1: Buero Roll Stop           =  Auf/ab Stop (1Bit) (für KNX Taster benutzt)
GA:4/1/20: Buero Roll Anfahren = ABB: Pos Behang anfahren (1Byte)
GA:4/1/21: Buero Roll Pos           = ABB: Pos Status Höhe (1Byte)

Randbedingungen: iOS:9.4.3, watchOS:2.2.2, Steuerung über Siri (watch) und EVE App auf iPhone/iPad

Im Prinzip geht es aber 2 Probleme:
1) Es geht nur "Schließe den Rollladen im Büro" und nicht "öffne den Rollladen im Büro". 
Obwohl "Stelle den Rollladen auf 100%" geht
2) steht bei mir bei Positionsstatus immer "Schließend" in der EVE App da ich ja aktuell "PositionState" in meiner Konfig-Datei dem KNX noch nicht zugeordnet habe bzw. mir auch nicht klar ist wie ich das konfigurieren soll/kann da diese Info ja über mehrere GAs verteilt ist.

hier der Auszug meiner Konfig:
          "name": "Bus Büro",
          "services": [
            {
              "type": "Lightbulb",
              "name": "Deckenleuchte",
              "On": {
                "Set": "2/1/8",
                "Listen": [
                  "2/1/8"
                ]
              },
              "Brightness": {
                "Set": "2/1/10",
                "Listen": [
                  "2/1/10"
                ]
              }
            },
            {
              "type": "Thermostat",
              "description": "iOS8 Thermostat type, supports CurrentTemperature, TargetTemperature, CurrentHeatingCoolingState ",
              "name": "Raumtemperatur",
              "CurrentTemperature": {
                "Listen": "3/4/9",
                "minValue": -20,
                "maxValue": 50
              },
              "TargetTemperature": {
                "Set": "3/4/2",
                "minValue": 5,
                "maxValue": 25
              }
            },
            {
              "type": "ContactSensor",
              "description": "sample contact sensor device",
              "name": "Büro Fenster geschlossen",
              "ContactSensorState": {
                "Listen": "1/2/1"
              }
            },
            {
              "type": "WindowCovering",
              "name": "Büro Rollladen",
              "TargetPosition": {
                "Set": "4/1/20R"
              },
              "CurrentPosition": {
                "Listen": "4/1/21R"
              }
            }
          ]
        }

Ist 1. hier aktuell nicht besser möglich (hatte es aber schon anders gelesen) und kann mir bei 2. jemand sagen ob und wie man das am besten hinbekommt?
misc2000

**Comment by thorsten-gehrig** [comment]
Hallo,
zwar reichlich spät - aber vielleicht liest du es ja noch?
Ich habe auch ABB Autoren im EG. Mittels externer Logik (auf dem HomeServer) rechne/ermittle ich mir den Status 0-100%... das 0/1 für die Position ist imho nicht ausreichend...
Gruß
Thorsten

**Comment by snowdd1** [comment]
@misc2000 
Ist so wie Thorsten geschrieben hat. Siri hat inzwischen ihren Schlaganfall auch verarbeitet, und versteht _Öffne Jalousie_ und _schließe Jalousie_ wieder.

**Comment by misc2000** [comment]
Danke Ihr beide,
ich werde mir dann jetzt das PositionState über einen Handler selbst berechnen sobald die Version 0.30 als stable da ist und ich die dann in meinem Produktiv-System einsetze. 
Gruß
Michael

**Comment by ctschach** [comment]
@misc2000 Ist zwar schon ein wenig her, aber würdest Du Deinen Handler mal teilen....wäre daran interessiert. Auch ich überlege, wie ich mir die Posiiton selber berechnen kann, da meine Aktoren stroh doof sind :-)

**Comment by misc2000** [comment]
Ein Teil meiner Handler (dieser) ist Teil des Releases von snowdd1 
Er liegt unter lib/addins einfach mal bei dir im Ordner nachsehen oder hier online:
[https://github.com/snowdd1/homebridge-knx/blob/master/lib/addins/Misc2000GarageDoorOpener.js](https://github.com/snowdd1/homebridge-knx/blob/master/lib/addins/Misc2000GarageDoorOpener.js)
Ich setze diesen seit 2 Jahren bei 2 Hörmann Toren erfolgreich ein.
In den ersten Zeilen des Handlers ist eine kleine Beschreibung...

**Comment by ctschach** [comment]
Ahh...danke, ja, den kenne ich :-)

Ich bin auf der Suche nach eine Lösung, um Positionsfahrten zu erlauben, obwohl meine Aktoren nur "Hoch", "Runter" und "Stop" erlauben. Also irgendwas, was über einen internen Timer läuft und dann im richigen Moment "Stop" sagt :-)

**Comment by misc2000** [comment]
ups es geht um Rollladen. Ich dachte um Garagentore :-) 
Da hatte ich mir auch mal was geschrieben aber im Moment nicht mehr im Einsatz, war nicht perfekt. Ich habe meine Aktoren gegen welche die Positionsfahrten können getauscht war einfach besser. Wenn ich aus dem Urlaub zurück bin müsste ich mal schauen ob ich da noch was finde...
