### ISSUE TITLE
Integration Alarmanlage

### ISSUE THREAD

**Issue by misc2000** [snowdd1/homebridge-knx-de#11]
Hallo,
ich habe eine Alarmanlage mit KNX-Interface deren Status wie auch wenn man das möchte die Schaltung über den  KNX Bus erfolgen kann.

Ich meine in der letzten Keynote gesehen zu haben, dass Alarmanlage in HomeKit spätestens ab iOS10 auch funktionieren sollten.
Liege ich da richtig und ist es geplant diese auch in Homebridge zu unterstützen?
Im Moment bilde ich den Status mit vielen einzelnen "ContactSensor" ab. 
Habe aber ein Problem, dass beim Starten von Homebridge die aktuellen Werte nicht vom Bus gelesen werden
....
"name": "Bus EMZ Status",
          "description": "Funktionen der Alarmanlage",
          "services": [
            {
              "type": "ContactSensor",
              "name": "Scharfgeschaltet",
              "ContactSensorState": {
                "Listen": "7/5/3R"
              }
            },
            {
              "type": "ContactSensor",
              "name": "Intern Scharf",
              "ContactSensorState": {
                "Listen": "7/5/0R"
              }
            },
            {
              "type": "ContactSensor",
              "name": "Extern Scharf",
              "ContactSensorState": {
                "Listen": "7/5/1R"
              }
            },
            {
              "type": "ContactSensor",
              "name": "Scharfschaltbereit",
              "ContactSensorState": {
                "Listen": "7/5/4R"
              }
            },
            {
              "type": "ContactSensor",
              "name": "Intern Alarm",
              "ContactSensorState": {
                "Listen": "7/6/0R"
              }
            },
            {
              "type": "ContactSensor",
              "name": "Extern Alarm Blitzleuchte",
              "ContactSensorState": {
                "Listen": "7/6/2R"
              }
....
MISC2000

**Comment by snowdd1** [comment]
@misc2000 
In der nächsten Version von homebridge-knx werden generisch alle Typen unterstützt werden.
Warum beim Start die Werte bei Dir nicht ausgelesen werden kann ich nicht sagen, guck mal in die ETS: Haben die ein "L" Lese-Flag?

**Comment by misc2000** [comment]
Hallo,
es waren wirklich die Lese-Flags die warum auch immer aktuell in der ETS gefehlt hatten. 
Danke, an das einfachste denke man selbst selten 👍 
Den Rest mache ich jetzt mit der 0.30 alpha

**Comment by snowdd1** [comment]
0.2.x ist aus und vorbei - sorry....
