### ISSUE TITLE
Cache Problem?

### ISSUE THREAD

**Issue by MrWichtig** [snowdd1/homebridge-knx-de#17]
im Eve werden mir die Devices mehrfach (z.B.: Bürolicht 10x angezeigt)...d.h,. beim Bürolicht sind 3 Adressen zugewiesen und alle werden 10x angezeigt  (insgesamt 30x)

sind dafür die Einträge in der knx_config.json gedacht?

{
    "knxd_ip": "192.168.1.1",
    "knxd_port": 6720,
    **"AllowWebserver": true,
    "AllowKillHomebridge": false,**
    "Devices": [    ]

ich habe diese bei mir hinzugefügt, jedoch scheint es so als läuft Eve in einer Endlosschleife (das "Suchrad" dreht sich die ganze Zeit und verbindet nicht mit homebridge.

oder besteht hier ein anderes Problem?

**Comment by ChrisSthler** [comment]
Denke mal das sind noch Lampen aus alt lasten.
verbessert mich wenn ich nicht rechte habe aber du musst einfach  <IP-deiner-homebridge>:18081/list 
also in deinen Fall  "192.168.1.1:18081/list" im Browser aufrufen und kannst die Zu vielen Devices löschen.
[https://github.com/snowdd1/homebridge-knx#removing-stale-accessories-from-homebridge-cache](url)

**Comment by MrWichtig** [comment]
...kann ich das von jedem beliebigen Browser aufrufen oder muss ich das vom Raspi (Browser) direkt aufrufen?

mein Raspi steht nämlich örtlich woanders wo ich keinen Monitor angeschlossen habe.

**Comment by ChrisSthler** [comment]
sollte doch von überall gehen wo du deinen Raspi erreichst.
denke doch die meisten werden sich per SSH drauf verbinden

**Comment by MrWichtig** [comment]
sorry wenn die Frage jetzt ein wenig verwirrend klingt....aber wie würde ich über ssh Web Zugang bekommen, sodass ich den Link 192.168.1.1:18081/list eingeben kann?

**Comment by ChrisSthler** [comment]
zb. deine SSH so startest mit dem -X `ssh -X pi@raspberrypi.local`
sieh dann erst mal aus wie sonst. aber dann `lxpanel&` eingibst dauert es einen Moment bis  Desktopumgebung geladen wurde.

Aber du solltest doch auch von deinen PC aus da drauf kommen oder nicht? [192.168.1.1:18081/list ](url)

**Comment by MrWichtig** [comment]
über den PC komme ich leider nicht drauf wenn ich den Link eingebe!  ???

aufs Raspi habe ich aber Zugriff (ssh, ftp, usw...)

auf meinem PC den LInk eingeben wäre auch mein erster Gedanke gewesen :-)

das mit der ssh starten über Putty funkt auch nicht wirklich :-(

```
pi@raspberrypi:~ $ lxpanel&
[1] 1186
pi@raspberrypi:~ $
(lxpanel:1186): Gtk-WARNING **: cannot open display:
```

**Comment by snowdd1** [comment]
Wie verbindest Du Dich denn mit dem raspberry, wenn Du ssh verwendest? Irgendeinen Namen oder IP verwendest Du doch wohl?

**Comment by MrWichtig** [comment]
über meinen Laptop mittels Putty.

ABER...ich habe mir gerade VNC einegerichtet auf mein Raspy und direkt am Raspi Browser versucht den Link einzugeben:

192.168.1.200:18081/list

...und auch hier bekomme ich  "This site can't be reached"

...scheint also so wenn ich hier gar nicht hinkomme.. (192.168.1.200 ist die IP meines Raspi's und auch in der knx_config.json eingetragen.......die IP 192.168.1.1 war nur kopiert von der Doku ;-))

**Comment by ChrisSthler** [comment]
was steht den in der conifg "AllowWebserver":**true**, oder **false** ??

**Comment by MrWichtig** [comment]
aso....das MUSS drinnenstehen?!

das habe ich wieder rausgenommen aus der knx_config.json weil meine Homebridge nicht erreichbar ist wenn das drinnen steht!

PASST...Funkt jetzt ! :-)
THX!!!

**Comment by snowdd1** [comment]
Das sollte aber nicht dazu führen das Homebridge nicht mehr startet. Ich habe das zur Zeit ständig an, weil mir oft Anpassungen an meiner knx_config.json einfallen. Ich habe auch das AllowKillHomebridge noch auf true, das ist einfach zu praktisch.
