### ISSUE TITLE
knx_config.json in anderem Verzeichnis

### ISSUE THREAD

**Issue by giase82** [snowdd1/homebridge-knx-de#18]
Hallo zusammen,

Ich habe vorhin mal etwas mit der 0.3.0 gespielt. Dabei ist mir aufgefallen, dass immer in ~/.homebridge nach der knx_config.json gesucht wird, egal wie ich homebridge starte.

In meinem Fall mit 
`homebridge -U /var/homebridge -D`

Kann man das umgehen bzw. ist das ein bug?

//giase

**Comment by MrWichtig** [comment]
HI,

die beiden Dateien müssen/sollten auch dort sein.....

https://github.com/snowdd1/homebridge-knx-de/issues/12

**Comment by giase82** [comment]
Sorry das muss ich wohl etwas genauer beschreiben.

Ich habe mehrere homebridges auf einem System (Raspberry Pi) laufen. Deshalb sind die configs getrennt, und zwar in:
`/var/homebridge
/var/homebridge2`

Ich denke im allgemeinen, dass homebridge-knx nach beiden Dateien (config.json, knx_config.json) im angegebenen Verzeichnis (homebridge -U **/var/homebridge** -D) suchen sollte, und nicht immer nach der knx_config.json in ~/.homebridge des aktuellen users. 

Geht das irgendwie oder ist das ein bug?

**Comment by MrWichtig** [comment]
mhm, da muss ich dann leider passen wie das aussieht mit 2 unterschiedlichen homebridges...sorry

**Comment by giase82** [comment]
Kein Problem. Vielleicht kann mir der Chef ja sagen, ob das Vielleicht nicht richtig durchgereicht wird?

Vielleicht fehlt einfach nur ein 

`User.setStoragePath = function(path) {
  customStoragePath = path;
}`

in user.js oder sowas?

**Comment by ChrisSthler** [comment]
Darf Mann mal fragen mit welchen Hintergedanken man das brauch? um die 100 Accessories bei HomeKit zum gehen? Oder Zwecks Verschiedener homebridges? also nicht nur KNX sondere andre?

**Comment by giase82** [comment]
Beides. Für einen Kumpel hab ich zwei homebridges weil mehr als 100 KNX-Geräte.
Bei ihm gäbe es dann auch ein Problem wenn beide homebridges auf die gleiche knx_config.json zugreifen.

Bei mir selbst habe ich die stabilen plugins (knx, ...) in einer homebridge, und die instabilen (harmonyhub, ...) in einer anderen, so dass mir nicht ständig KNX ausfällt nur weil mein HarmonyHub grade keine Verbindung schafft.

Makes sense?

**Comment by snowdd1** [comment]
Igitt, Ihr habt Recht. Ich bekomme den `-U /pfad/` Parameter gar nicht übergeben. Habe ich nicht getestet, weil ich immer als `pi` nur eine Instanz laufen lasse.

**Work-around** bis ich das geklärt habe:  
Wenn mehrere Instanzen gebraucht werden, auch mehrere User anlegen, die dann in der systemd-service-Datei drinstehen. Damit müsste für jeden User ein Verzeichnis bereitstehen.

**Comment by snowdd1** [comment]
Ok, probier mal Patch https://github.com/snowdd1/homebridge-knx/commit/5a70864da2c35957b4d1e5e2d1b4ed2dcaaae964

-->  @giase82

**Comment by giase82** [comment]
Schaut gut aus! Danke :)

**Comment by snowdd1** [comment]
Ok, kommt in die 0.3.2 rein. Vielleicht findet ja noch jemand was anderes, das wir mit reinpacken können. @giase82 vielleicht eine Jalousiesteuerung mit Tilt-Objekten?
