### ISSUE TITLE
Übersetzungen

### ISSUE THREAD

**Issue by snowdd1** [snowdd1/homebridge-knx-de#2]
Ich plane für die 0.3.0-Version von Homebridge-knx eine Web-Oberfläche zur Konfiguration.
Möchte jemand bei der Übersetzung der ganzen Homekit-Services & Characteristics helfen?

Danke und Gruß
Raoul

**Comment by snowdd1** [comment]
Hier die Vorlage für die Services: 

[Services-Translation.xlsx](https://github.com/snowdd1/homebridge-knx-de/files/158350/Services-Translation.xlsx)

**Comment by snowdd1** [comment]
Und die Vorlage für die Eigenschaften.

[Characteristics-Translation.xlsx](https://github.com/snowdd1/homebridge-knx-de/files/158406/Characteristics-Translation.xlsx)

Zusätzliche Detail, insbesondere wenn es an die Befüllung der Hilfetexte geht, kann man aus der Originaldatei ziehen: https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

Da stehen teilweise auch noch Beschränkungen drin, welche Werte zulässig sind, zum Beispiel hier: https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L78 dass ist beim Konfigurieren auch wichtig, versuche ich aber auch im Frontend anzuzeigen.

**Comment by ChrisSthler** [comment]
Hilft dir das weiter?

[Characteristics-Translation.xlsx](https://github.com/snowdd1/homebridge-knx-de/files/158566/Characteristics-Translation.xlsx)
[Services-Translation.xlsx](https://github.com/snowdd1/homebridge-knx-de/files/158567/Services-Translation.xlsx)

**Comment by snowdd1** [comment]
Danke, jetzt muss ich nur noch den Teil bauen, der das auch nutzt... :-)
