### ISSUE TITLE
knx_config.json SUB/UUID

### ISSUE THREAD

**Issue by MrWichtig** [snowdd1/homebridge-knx-de#20]
ich habe es so verstanden, dass sich die knx_config.json wenn man ein neues Gerät hinzufügt selbts eine eindeutige SUB und UUID Nummer vergibt?! richtig?

wobei ich mir nicht sicher bin, wenn ich ein neues Gerät in die*.json Datei hinzufüge was ich im File angeben muss, dass die Nummer generiert wird?!

z.B.:
```

{
            "DeviceName": "Test Lampe",
            "Services": [
                {
                    "ServiceType": "Lightbulb",
                    "ServiceName": "Test Lampe",
                    "Characteristics": [
                        {
                            "Type": "On",
                            "Set": [
                                "1/2/3"
                            ],
                            "Listen": [
                                "1/3/4"
                            ],
                            "DPT": "DPT1"
                        },
                        {
                            "Type": "Brightness",
                            "Set": [
                                "1/5/8"
                            ],
                            "Listen": [
                                "1/7/10"
                            ],
                            "DPT": "DPT5.001"
                        }
                    ],
                    "subtype": "SUB_12389a71-f76f-4507-bc00-6c2c1c5fdc44"
                }
            ],
            "UUID": "5a1fd0c7-0012-4046-aa67-1f0b56559c6d"
        },        
```

muss ich nur z.B.: **"subtype":**  oder z.B.: **"UUID":** (ohne einer langen eindeutigen Nummer) angeben und der Rest wird dann selber angefügt wenn man homebridge neu startet?

oder kann ich da irgend eine "fiktive" Nummer vergeben?

wie erfolgt das?

**Comment by snowdd1** [comment]
Guter Punkt, steht noch nicht in der Doku. **Entferne** beim Kopieren einfach die Einträge, dann sind sie wieder "neu" und bekommen eine automatisch zugewiesen.

**Comment by MrWichtig** [comment]
soll der ganze Eintrag entfernt werden:
**_"subtype":_ "SUB_12389a71-f76f-4507-bc00-6c2c1c5fdc44"
"_UUID":_ "5a1fd0c7-0012-4046-aa67-1f0b56559c6d"**

oder nur die jeweilige Nummer von SUB u. UUID?
_"SUB_12389a71-f76f-4507-bc00-6c2c1c5fdc44
 "5a1fd0c7-0012-4046-aa67-1f0b56559c6d"_

sofern ersteres (sprich der ganze Eintrag gelöscht werden muss), kann ich die Klammern stehen lassen oder müssen die auch jeweils dann entfernt werden vor "subtype" und vor "UUID" ?

lg
Wolfi

**Comment by MrWichtig** [comment]
habs schon rausbekommen :-)

es darf nur die Nummer gelöscht werden und nach Neustart wird dann eine neue Nummer eingetragen.

so muss es aussehen wenn Feld freigelassen werden soll:

```

"subtype": ""
"UUID": ""
```

**Comment by snowdd1** [comment]
Geht beides. Du kannst auch den Schlüssel mit entfernen (und das Komma davor nicht vergessen!)

**Comment by tunneltruppe** [comment]
Entschuldigung, ist hier glaube ich richtiger:
Guten Morgen,
ich habe ja zum Glück die homebridge am laufen.
Auch sind die ersten Einträge in der knx_config.json.
Die alten/ Mustereinträge (hatte es mit einer laufenden Datei als erstes probiert)
sind gelöscht.
Aber es tauchen immer noch die Mustereinträge auf.
Hallt die cachedAccessories Datei gelöscht und einmal angepasst.
Aber es kommen immer alle Einträge wieder rein.
Was mache ich oder habe ich da flasch gemacht?
Auszug:
[{"plugin":"homebridge-knx","platform":"KNX","displayName":"Arbeitszimmerlampe","UUID":"2a85c643-e88d-40ea-8ba2-cd04a66b84ec",.....
..und noch mal DANK Raoul
Gruß Marcus

**Comment by snowdd1** [comment]
@tunneltruppe 
Das habe ich nicht verstanden. Du willst Deine homebridge wieder auf NULL zurücksetzen? So als ob sie das erste Mal startet?  

Dann:  
1. homebridge aus Home app (oder Elagato Eve, etc) aus dem Haus entfernen. Also dort "Gerät entfernen" wählen
2. In dem home-Verzeichnis (.homebridge) die Ordner `persist` und `accessories` restlos löschen
3. homebridge neustarten

**Comment by tunneltruppe** [comment]
...Du hast es richtig verstanden!!! Jupp auf NULL setzen!!!
Genau das war so!! So herum!!
Hatte zwar alles (mit Ordner) gelöscht, aber nicht vorher die homebridge
gelöscht!!!
Vielen DANK für die viele ARBEIT hier!!!
Gruß Marcus
