### ISSUE TITLE
Reihenfolge

### ISSUE THREAD

**Issue by ChrisSthler** [snowdd1/homebridge-knx-de#22]
Ist es eigentlich egal welche Reihenfolge ServiceType, ServiceName und Handler haben?

"ServiceType": "ContactSensor",
"ServiceName": "Vasistas",
"Handler": "ContactSensor",

 "ServiceType": "WindowCovering",
  "Handler": "GiraAwningActuator",
  "ServiceName": "Porch Awning",

Ist in den Add-Ins nämlich nicht gleich...

**Comment by snowdd1** [comment]
Ja. Innerhalb der Klammern {} gibt es keine Reihenfolge.
