### ISSUE TITLE
Beispiele für alle unterstützten Objekte...

### ISSUE THREAD

**Issue by ctschach** [snowdd1/homebridge-knx-de#24]
Hallo Ihr Lieben,

gibt es irgendwo ein Beispiel, welche Objekte bis jetzt unterstützt werden? Lampen und Temperaturen habe ich selbst rausgefunden. Aber was gibt es noch? Die Rollo Unterstützung wie aus der Beispiel-Konfig läuft bei mir nicht. Habe aber auch doofe Aktoren, die nur auf- und zu können. Bei "1" sind sie zu, bei "0" sind die auf. Geht das irgendwie, oder muss ich da KNX Objekte intern umsetzen?

Generell wäre es interessant zu wissen, welche anderen Objekte noch unterstützt werden.

Danke....

**Comment by snowdd1** [comment]
Guten Morgen,
grundsätzlich unterstützt die Version 0.3 _alle_ homekit-Dienste. **_Aber_**: Natürlich lassen sich nicht alle KNX-Aktoren/Sensoren problemlos auf die HomeKit-Welt mappen. Daher gibt es die Add-in, sie [Wiki](https://github.com/snowdd1/homebridge-knx-de/wiki/Add-Ins).  

Komplett ohne extra Übersetzer gehen die meisten Lichter (An/Aus DPT1, Helligkeit DPT5.001), viele Bewegungsmelder (DPT1), Reed-Kontakte/Kontaktsensoren (DPT1), Temperatursensoren (DPT9).  

Was zur Zeit gar nicht geht, sind Geräte die nicht absolut angesteuert werden können: Dimmer, die nur heller/dunkler (DPT3) oder Jalousien die nur höher/niedriger (DPT3) können.  

Bist Du sicher, dass Du Deinen Aktor nicht so konfigurieren kannst, dass er auch eine Position annimmt, und eine Rückmeldet?  

Gruß
Raoul

**Comment by ChrisSthler** [comment]
Wäre das vielleicht auch einen Wiki Eintrag wert?
Wenigsten eine Kleine aufliestung ServiceType mit den Characteristics den KNX dpts unterstützt. (aktuelle). und Ohne besonderes Mapping.

**Comment by ctschach** [comment]
Ja, leider sind meine KNX Aktoren strohdoof :-)

Wollte das immer mal per Software auf dem Steuerrechner implementieren - habe ich aber bis jetzt nie geschafft....die liebe Zeit :-)

Geht also nur hoch, runter und stop. So gesehen müsste ich da was mit LinKNX umsetzen.

**Comment by snowdd1** [comment]
Grundsätzlich könntest du das, was andere halb-dumme Aktoren machen (Zeit messen um gefahrenen Weg u ermitteln) natürlich auch in einem Add-in programmieren!
