### ISSUE TITLE
Reverse Funktion

### ISSUE THREAD

**Issue by MrWichtig** [snowdd1/homebridge-knx-de#25]
Hallo,

ich benötige bei einer Szene (DPT1....OHNE Handler) eine Reverse Funktion. Nach meinem Verständnis sollte ja wenn kein Handler angegeben das Reverse funktionieren?!

habe jetzt schon einiges ausprobiert aber so wirklich klappen möchte das ganze nicht.......hätte hierzu wer einen Tipp was ich falsch mache?

```
{
"knxd_ip": "192.168.1.200",
"knxd_port": 6720,
"AllowWebserver": true,
"AllowKillHomebridge": true,
"Devices": [
{
"DeviceName": "Szene eins",
"Services": [
{
"ServiceType": "Switch",
"ServiceName": "Szene eins",
"Characteristics": [
{
"Type": "On",
"Set": [
"17/0/1"
],
"Reverse":true
}
],
"subtype": "SUB_76f31b7a-7ea6-4b33-87dc-1ba69d39c66a"
}
],
"UUID": "d42ed6ac-0f43-428d-b7e4-038941b62b92"
},
```

**Comment by snowdd1** [comment]
Nein, das sieht eigentlich richtig aus. Kannst du ein paar Zeilen aus dem Log zur Verfügung stellen, die geschrieben werden wenn Du den Schalter in der App betätigst?

**Comment by MrWichtig** [comment]
sollte das log nicht unter _**var/log/homebridge.log**_ zu finden sein?

oder ist das bei homebridge 0.3.x anders?

muss ich bei Änderungen (z.B.: Reverse) in der knx_config.json zuerst noch Cache, etc... löschen?

**Comment by snowdd1** [comment]
Das log ist je nach Installation bzw. startart an unterschiedlichen Stellen. 

Bei systemd wie im Wiki beschrieben gibt es das log mit `journalctl` siehe Wiki.

**Comment by snowdd1** [comment]
Beim Einfügen von Reverse muss der Cache nicht gelöscht werden, dass sollte so gehen.

**Comment by MrWichtig** [comment]
mit was öffnet man das journalctl? auch notepad?  im notepad sehe ich nur "verwirrte" Zeichen :-)
dann kann ich es gerne zur Verfügung stellen ;-)

**Comment by MrWichtig** [comment]
bekomme das keine journal files gefunden wurden?!

```
pi@raspberrypi:~ $ sudo usermod -a -G systemd-journal pi
pi@raspberrypi:~ $ journalctl -u homebridge.service
**No journal files were found.**
pi@raspberrypi:~ $ journalctl -u homebridge.service
**No journal files were found.**
pi@raspberrypi:~ $

```

**Comment by snowdd1** [comment]
Merkwürdig. Hast du mal `sudo journalctl -u homebridge` versucht? heißt der Service bei dir überhaupt `homebridge`? Der müsste ja so (als unit glaube ich) in der Service-Definition drinstehen.

**Comment by MrWichtig** [comment]
Hi Raoul,

Ja mit "sudo" hats funktioniert....verzeih mir meine geringen Linuxkenntnisse :-)


```
Nov 28 14:21:14 raspberrypi homebridge[516]: ---iterating--------------------
Nov 28 14:21:14 raspberrypi homebridge[516]: address: 17/0/1
Nov 28 14:21:14 raspberrypi homebridge[516]: reverse: true
Nov 28 14:21:14 raspberrypi homebridge[516]: dptype: DPT1
Nov 28 14:21:14 raspberrypi homebridge[516]: ================================
Nov 28 14:21:14 raspberrypi homebridge[516]: [11/28/2016, 2:21:14 PM] [homebridge-knx.KNX]  (reverse)
Nov 28 14:21:14 raspberrypi homebridge[516]: [11/28/2016, 2:21:14 PM] [homebridge-knx.KNX] DEBUG got dest=34817
Nov 28 14:21:14 raspberrypi homebridge[516]: [11/28/2016, 2:21:14 PM] [homebridge-knx.KNX] knxAccess.knxwrite: knx data sent: Value 0 for GA 17/0/1
Nov 28 14:21:14 raspberrypi homebridge[516]: [11/28/2016, 2:21:14 PM] [homebridge-knx.KNX] knxAccess.writeValueHK(1,On,DPT1,false)
Nov 28 14:21:14 raspberrypi homebridge[516]: [11/28/2016, 2:21:14 PM] [homebridge-knx.KNX] knxAccess.writeValueHK: Format bool
Nov 28 14:21:14 raspberrypi homebridge[516]: [11/28/2016, 2:21:14 PM] [homebridge-knx.KNX] BOOL:[On]: Received value from KNX handler:1 of type DPT1
Nov 28 14:21:37 raspberrypi homebridge[516]: ---iterating--------------------
Nov 28 14:21:37 raspberrypi homebridge[516]: address: 17/0/1
Nov 28 14:21:37 raspberrypi homebridge[516]: reverse: true
Nov 28 14:21:37 raspberrypi homebridge[516]: dptype: DPT1
Nov 28 14:21:37 raspberrypi homebridge[516]: ================================
Nov 28 14:21:37 raspberrypi homebridge[516]: [11/28/2016, 2:21:37 PM] [homebridge-knx.KNX]  (reverse)
Nov 28 14:21:37 raspberrypi homebridge[516]: [11/28/2016, 2:21:37 PM] [homebridge-knx.KNX] DEBUG got dest=34817
Nov 28 14:21:37 raspberrypi homebridge[516]: [11/28/2016, 2:21:37 PM] [homebridge-knx.KNX] knxAccess.knxwrite: knx data sent: Value 1 for GA 17/0/1
Nov 28 14:21:39 raspberrypi homebridge[516]: ---iterating--------------------
Nov 28 14:21:39 raspberrypi homebridge[516]: address: 17/0/1
Nov 28 14:21:39 raspberrypi homebridge[516]: reverse: true
Nov 28 14:21:39 raspberrypi homebridge[516]: dptype: DPT1
Nov 28 14:21:39 raspberrypi homebridge[516]: ================================
Nov 28 14:21:39 raspberrypi homebridge[516]: [11/28/2016, 2:21:39 PM] [homebridge-knx.KNX]  (reverse)
Nov 28 14:21:39 raspberrypi homebridge[516]: [11/28/2016, 2:21:39 PM] [homebridge-knx.KNX] DEBUG got dest=34817
Nov 28 14:21:39 raspberrypi homebridge[516]: [11/28/2016, 2:21:39 PM] [homebridge-knx.KNX] knxAccess.knxwrite: knx data sent: Value 0 for GA 17/0/1
Nov 28 14:21:55 raspberrypi homebridge[516]: [11/28/2016, 2:21:55 PM] [homebridge-knx.KNX] knxAccess.writeValueHK(1,On,DPT1,false)
Nov 28 14:21:55 raspberrypi homebridge[516]: [11/28/2016, 2:21:55 PM] [homebridge-knx.KNX] knxAccess.writeValueHK: Format bool
Nov 28 14:21:55 raspberrypi homebridge[516]: [11/28/2016, 2:21:55 PM] [homebridge-knx.KNX] BOOL:[On]: Received value from KNX handler:1 of type DPT1
```

**Comment by snowdd1** [comment]
Das Reverse kommt auch an. Sollte also m. E. auch umgedreht werden. 

Was war nochmal genau das Problem?

**Comment by MrWichtig** [comment]
Problem war/ist, dass wenn ich kein Reverse beim Device konfiguriert habe genau das gleiche ist wenn ich ein Reverse konfiguriert habe :-)

z.b.: Szene lässt sich nur AUS schalten.

Beispiel in der Praxis:
ich spreche Hey Siri,

**Szene 1 EIN**..........nix tut sich

**Szene 1 AUS**........es tut was es soll

und genau das würde ich gerne umdrehen mit Reverse.....Problem ist nur, dass die Szene **MIT** und **OHNE** Reverse immer nur bei **AUS** funktioniert

**Comment by MrWichtig** [comment]
HI,

Gelöst!

habe gestern nochmal alles gecheckt....Fehler ist nicht das Reverse, sondern habe ich bei mir lokal bei dieser Szene (in der Visu) das Eingangsobjekt auf "EIN" stellen müssen. War auf "AUS" gestellt.

nachdem es bei der homebridge 0.2.x ohne Umstellung funktioniert hat habe ich hier als erstes auch gar nicht gesucht gehabt.

@Raoul...trotzdem Danke für Deinen Support!

**Comment by snowdd1** [comment]
Das ist richtig - aber man sollte `Reverse` trotzdem nutzen können, daher muss ich es mir ja dennoch ansehen warum es nicht ging!

**Comment by snowdd1** [comment]
https://github.com/snowdd1/homebridge-knx/issues/67 erledigt.
