### ISSUE TITLE
Negative Temperaturen

### ISSUE THREAD

**Issue by giase82** [snowdd1/homebridge-knx-de#29]
Hallo zusammen,

Nachdem der Winter eingekehrt ist, ist mir neulich aufgefallen, dass mein Aussentemp-Sensor immer einen Fehler meldet. Ich gehe schwer davon aus, dass es an den negativen Temperaturen liegt.

Deswegen mal eine generelle Frage:
In der “CurrentTemperature” Characteristic steht
    maxValue: 100,
    minValue: 0,

Kann ich das auch außerhalb dieser Grenzen beeinflussen? Ich hatte bis jetzt immer den Eindruck als ginge das nur innerhalb der Grenzen, die in HomeKitTypes.js definiert sind...
Wenn ja, kann ich da mal ein Syntax-Beispiel haben?

Danke,
//Christof

**Comment by snowdd1** [comment]
Sorry, das ist ein undocumentiertes Feature in Commit https://github.com/snowdd1/homebridge-knx/commit/faf1cf7f36e78e0e6091861a4a6d8988f77afa4f  

Muss die Doku anpassen.  

Sieht ungefähr so aus (kann gerade nicht zu Hause nachsehen):

(Verwende Beispiel von Tqm aus Beitrag https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/diy-do-it-yourself/998030-homebridge-knx-0-3-0-alpha-apple-homekit-interface/page10 )

```json
          "ServiceType": "TemperatureSensor",
          "ServiceName": "Aussentemperatur Nord",
          "Characteristics": [
            {
              "Type": "CurrentTemperature",
              "Listen": [
                "0/0/1"
              ],
              "MaxValue":60,
              "MinValue":-20
            }
          ]
        }
```
Wichtig: Ich habe die Groß-Kleinschreibung von v0.2 an die anderen Schlüsselwörter in v.0.3 angepasst!!! 
~~minValue~~ ==> **"MinValue"**
~~maxValue~~ ==> **"MaxValue"**

**Comment by giase82** [comment]
Super, läuft! Ich denk ich hatte das Groß-/Kleinschreibungs Problem und dachte deswegen es geht nicht.

**Comment by snowdd1** [comment]
Erledigt mit https://github.com/snowdd1/homebridge-knx/commit/5168a13e1b42fbd61c3a5ca3dd4ed7087ee54098
