### ISSUE TITLE
100 Accessories-Fehler

### ISSUE THREAD

**Issue by snowdd1** [snowdd1/homebridge-knx-de#3]
Die 100 (bzw. die 99) spielt für Homekit eine wichtige Rolle:
Jede Brücke (z.B. Homebridge) kann maximal 99 (plus Bridge=100) Accessories bei Homekit anmelden, der Versuch ein weiteres Gerät anzubieten führt dazu, dass sofort die ganze Bridge nicht mehr erreichbar ist, ggf. sogar von Homekit gesperrt wird, so dass selbst nach den entfernen des 100. Geräts die Bridge nicht mehr erreichbar ist.

Da jedes Gerät (Accessory/Device) in Homekit aber bis zu 100 Services haben darf (Achtung: Es sind bereits intern für jedes Gerät ein paar Services  reserviert, so dass m.E. 97 zur Verfügung stehen), lässt sich unter Umständen die Anzahl der Accessories/Devices drastisch reduzieren.

Voraussetzungen
- Die verwendete iOS-App kann mit mehreren gleichen Services in einem Gerät umgehen (EVE konnte das am Anfang nicht und kam immer durcheinander)
- Die Services sind alle im gleichen Raum, da man nur Accessories einem Raum zuordnen kann.

**Comment by ChrisSthler** [comment]
Wie sieht den im Moment die vorgehensweise aus wenn Mann mehr als 100 (99) Accessories Möchte/brauche?
Eine weitere Homebridge Instanz auf einen weiteren RasPi oder nur einen zweiten(3ten) User nehmen?

**Comment by snowdd1** [comment]
Hallo @ChrisSthler ,
drei Möglichkeiten:
- Die **einfachste** Lösung (mache ich inzwischen auch): Für jeden Raum (oder oder virtuellen Raum, bei mir z.B. "Parkplatz") dem man Geräte zuordnen möchte, nur **1 "Sammelgerät"** anlegen. So habe ich ein Gerät namens Küche, in dem ich mehrere "Lightbulb" Services, zwei "WindowCovering" Services, einen Temperatursensor und zwei Fensterkontakte untergebracht habe. In :apple: Home und Eve klappt das dann auch sehr gut, da diese im Zweifelsfall das "Device" gar nicht anzeigen, sondern nur die Services.
- Mehrere User oder/und Verzeichnisse: **zweiteinfachste** Lösung. Seit [Version 0.3.2](https://github.com/snowdd1/homebridge-knx/tree/v0.3.2) funktioniert auch das **-U <pfad>** parameter wieder, so dass man nur die Konfigurationen in mehrere Verzeichnisse stecken muss (Leider ist das nur in einem Nebensatz dokumentiert, siehe https://github.com/nfarina/homebridge#plugin-development).
- Mehrere HomeBridges geht immer, in der "bridge" section der config.json darauf achten, dass die auf gar keinen Fall die gleichen "name" und "username" haben. Man braucht mehr Hardware, und muss alle Instanzen einzeln aktualisieren. Daher aus meiner Sicht die meiste Arbeit.

Gruß
Raoul

**Comment by ChrisSthler** [comment]
Hallo Raoul,

Danke für die Schnelle Antwort. Möglichkeit Zwei und Drei habe ich mir ja schon gedacht.
Aber die Erste klingt doch sehr Interessant, Kannst du mal ein Exempel zu der "einfache" Lösung Bereitstellen.

Mit freundliche Grüßen

**Comment by snowdd1** [comment]
Ungefähr so: 
1 Device "Arbeitszimmer" mit Licht und Rollo

``` json
{
    "knxd_ip": "192.168.178.1",
    "knxd_port": 6720,
    "Devices": [
        {
            "DeviceName": "Arbeitszimmer",
            "Services": [
                {
                    "ServiceType": "Lightbulb",
                    "ServiceName": "Bürolampe",
                    "Characteristics": [
                        {
                            "Type": "On",
                            "Set": [
                                "1/3/5"
                            ],
                            "Listen": [
                                "1/3/5"
                            ]
                        }
                    ]
                },
                {
                    "ServiceType": "WindowCovering",
                    "Handler": "GiraJalousieActuator",
                    "ServiceName": "Büro-Rollo",
                    "Characteristics": [
                        {
                            "Type": "TargetPosition",
                            "Set": [
                                "2/3/46"
                            ],
                            "DPT": "DPT5"
                        },
                        {
                            "Type": "CurrentPosition",
                            "Listen": [
                                "2/3/26"
                            ]
                        },
                        {
                            "Type": "PositionState"
                        }
                    ],
                    "KNXObjects": [
                        {
                            "Type": "ShutterMove",
                            "Listen": "2/3/6",
                            "DPT": "DPT1"
                        }
                    ],
                    "KNXReadRequests": [
                        "2/3/26",
                        "2/3/46"
                    ]
                }
            ]
        }
    ]
}
```

**Comment by ChrisSthler** [comment]
ach jetzt glaube ich hat es Klick gemacht.
Das "Sammelgerät" ist immer der Raum und im Raum selber sind dann die ServiceTypes erst die Eigentlichen "Device"

Richtig?

**Comment by snowdd1** [comment]
Richtig. Das Raum=Device ist hat den Vorteil, dass man dann die Zuweisung in HomeKit einfacher machen kann "Arbeitszimmer" ist ein Gerät im "Arbeitszimmer" - intuitive, isn't it?  

Ansonsten kann man es natürlich auch einfach "ac4314815481554" nennen, da die Device-Namen inzwischen in den Apps überwiegend ignoriert werden (komplett sogar in "Home").

"Services are the prime HomeKit objects" hat KhaosT geschrieben, als er die [Grundlagen für homebridge entwickelte](https://github.com/khaost/hap-nodejs)

**Comment by baumph** [comment]
Hallo Snowdd1,
wenn man die Accessories so gruppiert, kann man dann in der Home App die ServiceTypes als einzelne Tiles anzeigen lassen? Oder sorgt das auch dafür, dass man über die 100 Accessories kommt?

**Comment by snowdd1** [comment]
Sowohl als auch. Allerdings werden seit iOS 13 die „accessories“ wieder als eigene Geräte angezeigt, und standardmäßig nur der erste Service als Kachel angezeigt. In der Home App auf Telefon und iPad lässt sich das ändern, nicht aber für die Watch!
Daher werde ich meine Konfiguration wieder ändern (nach 3 Jahren vielleicht auch ok)

**Comment by snowdd1** [comment]
Man kann ja mehrere Instanzen parallel starten. Eine für jede Etage zum Beispiel.
