### ISSUE TITLE
Gruppenadressen größer 15/7/255; war: Update 0.3.4-- knx_config.json nicht kompatibel ? 

### ISSUE THREAD

**Issue by MrWichtig** [snowdd1/homebridge-knx-de#31]
HI,

ich habe vor ein paar Tagen das Update homebridge u. homebridge-knx gemacht. Nach einem Update wurde homebridge nicht mehr gefunden (eve, etc...)

habe hier verschiedenste Szenarien probiert (komplette Neuinstallationen inkl. Betriebssystem, etc..., Updates auf verschiedene Art u. Weisen......)

nun bin ich drauf gekommen, dass die _knx_config.json_ das Problem ist.

wenn ich nach Update oder Neuinstallation eine Standard _knx_config.json_ einspiele wird homebridge gefunden. wenn ich eine bestehende die ich bisher genutzt habe einspiele wird homebridge nicht gefunden. Ist nachvollziehbar.

die _knx_config.json_  habe ich sicherheitshalber auch nochmal im Json Validator überprüft "Validate".

Aber nichts desto trotz die bestehende _knx_config.json_ habe ich bis vor dem Update auf die neueste Version im Einsatz gehabt und hat auch ohne Probleme funktioniert!

gibt es dafür eine Erklärung oder muss man seit dem letzten Update noch irgend etwas beachten?

lg

**Comment by dosordie** [comment]
Hallo,

das hört sich so an als ob du von der v0.2... zur 0.3.4 wechselst. In dem fall musst du (leider) die komplette Konfig. umschreiben da sich das Format geändert hat.

Solltest du schon bei er 0.3... gewesen sein, kann ich´s mir nicht erklären.

**Comment by MrWichtig** [comment]
Hi,

Nöp.....ich war die ganze Zeit schon auf 0.3.x. Version !!

**Comment by MrWichtig** [comment]
HI,

ich bin nach stundenlangem ausprobieren jetzt auf die Fehler gestoßen was in der knx_config.json Datei seit VersionsUpdate 0.3.4 die Probleme verursacht. (ist auch nachvollziehbar)

in meinem Fall sind das folgende beiden Service Typen:

Service Typ "Switch" und Service Typ "WindowCovering"


sobald einer der beiden Typen bei mir in der knx_config.json beinhaltet ist wird die homebridge nicht gefunden.

ich habe 2 Beispiele aus meiner *.json angehängt....evtl. kann sich Raoul oder auch ein anderes Mitglied hier erklären woran es liegt. Das hat wie gesagt in den Vorgänger Versionen der 0.3.x Versionen bei mir funktioniert.

_Beispiel Service Typ_ **"Switch"**

`        {
            "DeviceName": "Musik Essen",
            "Services": [
                {
                    "ServiceType": "Switch",
                    "ServiceName": "Musik Essen",
                    "Characteristics": [
                        {
                            "Type": "On",
                            "Set": [
                                "20/1/1"
                            ]
                        }
                    ],
                    "subtype": "SUB_2d6209d7-7f6b-4ec8-924a-9e4d24f780d0"
                }
            ],
            "UUID": "ebdac8fd-4371-42fe-b86c-0c9bc8a0fd6c"
        },
`


_Beispiel Service Typ_ **"WindowCovering" (ohne Handler)**

`        {
            "DeviceName": "Rollladen Essen",
            "Services": [
                {
                    "ServiceType": "WindowCovering",
                    "ServiceName": "Rollladen Essen",
                    "Characteristics": [
                        {
                            "Type": "TargetPosition",
                            "Set": [
                                "4/4/0"
                            ],
                            "DPT": "DPT5"
                        },
                        {
                            "Type": "CurrentPosition",
                            "Listen": [
                                "4/5/0"
                            ]
                        },
                        {
                            "Type": "PositionState"
                        }
                    ],
                    "KNXObjects": [
                        {
                            "Type": "ShutterMove",
                            "Listen": "0/0/0",
                            "DPT": "DPT1"
                        }
                    ],
                    "KNXReadRequests": [
                        "4/4/0",
                        "4/5/0"
                    ],
                    "LocalConstants": {
                        "SomeVariable_notUsedHere": "SomeValue",
                        "OtherBlinds_notUsedHere": "OfficeShutter"
                    },
                    "subtype": "SUB_78d9fb9e-8447-4c70-882d-3272636c6517"
                }
            ],
            "UUID": "5bfb236f-f416-44c9-8b72-ef26659b3874"
        },
`

**Comment by ChrisSthler** [comment]
hat jetzt nicht direkt mit deinen Problem zutun was mich aber interessiert (geht bei mir nicht) ist dein "Musik Essen" des kannst du nur über die App starten oder? Siri leitet mich nämlich immer in die Musik App um wenn ich das probiere. habe es dann selber mit Lautsprecher Staat Musik gelöst...

Aber des mit dem WindowCovering hatte ich auch war unter anderen ein Probleme warum es bei mir nicht gelaufen ist ich dachte es liegt daran weil ich es auch ohne Händler gemacht hatte.

was für Fehler Meldungen bekommst du wenn du es innen hast also Rollo oder Switch?

**Comment by MrWichtig** [comment]
Hi,

also die Sprachsteuerung für Musik (Squeezebox) und Rollladen über Siri hat bei mir schon funktioniert per Sprachbefehl. (allerdings nur EIN/AUS.....was für mich aber schon OK ist für den Anfang :-) )

alles wie gesagt aber nur mit der Vorgänger "homebridge" Version.

ich habe beide homebridge Versionen ( beides 0.3.x Versionen) am laufen (auf unterschiedlichen SD cards) und kann daher auch relativ gut testen.

was genau meinst Du mit Fehlermeldung welche ich bekomme/ sollte?

bei mir ist das Problem bei der neuesten Version der homebridge, dass die knx_config.json nicht geladen wird bzw. homebridge gar nicht gefunden wird. Sobald diese 2 Service Typen nicht enthalten sind wird sie sofort angezeigt.

**Comment by ChrisSthler** [comment]
Hi,

wie startest du den deine Homebridge? über `sudo systemctl start homebridge` oder  nur über `homebridge` wenn ich das zweite mache sehe ich am ende wie HB abstürzt bzw. mit was sie Probleme hat.
Kommt dann zb. sowas dabei raus....
> Dec 08 20:28:18 raspberrypi homebridge[1463]: [12/8/2016, 8:28:18 PM] [homebridge-knx.KNX] ERR no valid group address structure (31/7/255): second triple exceeds 7
Dec 08 20:28:18 raspberrypi homebridge[1463]: /usr/lib/node_modules/homebridge-knx/lib/characteristic-knx.js:112
Dec 08 20:28:18 raspberrypi homebridge[1463]: throw (new Error("CONFIG ERROR").message='Invald group Address: '+ cGA);
Dec 08 20:28:18 raspberrypi homebridge[1463]: ^
Dec 08 20:28:18 raspberrypi homebridge[1463]: Invald group Address: 1/8/22

was musst du Siri sagen um Musik zu starten? Wenn ich zb. versuche meine Yamaha AV-Receiver Ein/Aus zuschalten leitetet mich Siri immer zur Apple Musik App um.

**Comment by MrWichtig** [comment]
....also prinzipiell wird bei mir die Homebridge über die Autostart gestartet bei einem Neustart des Raspis.

...und ja wenn ich über "homebridge" Befehl manuell starte kommen da auch ein paar solche Fehlermeldungen wie bei Dir oben beschrieben, was sich aber bisher nicht auf die Funktionen ausgewirkt hat. 


bez. Sprachbefehl:
ich kann es auf 2 Varianten machen.

entweder:
Hey Siri, Musik essen EIN/AUS

oder:
Hey Siri, Schalte Musik Essen EIN/AUS

lg

**Comment by ChrisSthler** [comment]
also mir haben bisher immer die Fehlermeldungen weiter geholfen den Fehler zu finden.
war zb. mal außerhalb des zulässigen Bereichs mit meinen GAs...
zeige doch mal was bei dir führ eine Meldung kommt wenn es nicht startet.

aber des Mit der Musik verstehe ich echt nicht...... egal ob am iPhone, Watch oder iPad öffnet er mir sofort die Musik App hast du da irgendwelche besonderen Einstellungen?
Ich dachte auch immer das ich da nicht der einzige bin den es so geht. ;-(

**Comment by MrWichtig** [comment]
...hier die Fehlermeldung wenn ich z.B.: Musik Essen in der knx_config.json drinnen habe:

> ---iterating--------------------
Type: On
Set.0: 0/0/5
Listen.0: 11/0/4
================================
INFO registerSingleGA 11/0/4
[1/3/2017, 12:30:34 PM] [homebridge-knx.KNX] Done with [Licht Kellerabgang] acce                                                                                           ssory
[1/3/2017, 12:30:34 PM] [homebridge-knx.KNX] Reading from config: Device/Accesso                                                                                           ry 44 of 44
[1/3/2017, 12:30:34 PM] [homebridge-knx.KNX] Service constructor called
[1/3/2017, 12:30:34 PM] [homebridge-knx.KNX] ServiceType defined
[1/3/2017, 12:30:34 PM] [homebridge-knx.KNX] ServiceType known as function
[1/3/2017, 12:30:34 PM] [homebridge-knx.KNX] Did not find restored service for:                                                                                            Musik Essen
[1/3/2017, 12:30:34 PM] [homebridge-knx.KNX] Created service: Musik Essen
[1/3/2017, 12:30:34 PM] [homebridge-knx.KNX] Preparing Characteristics: 1
[1/3/2017, 12:30:34 PM] [homebridge-knx.KNX] On
[1/3/2017, 12:30:34 PM] [homebridge-knx.KNX] Adding characteristic...
[1/3/2017, 12:30:34 PM] [homebridge-knx.KNX] CharacteristicKNX.Constructor
---iterating--------------------
Type: On
Set.0: 20/1/1
================================
[1/3/2017, 12:30:34 PM] [homebridge-knx.KNX] ERR no valid group address structur                                                                                           e (15/7/255): first triple exceeds 15

/usr/lib/node_modules/homebridge-knx/lib/characteristic-knx.js:121
                                                throw (new Error("CONFIG ERROR")                                                                                           .message='Invald group Address: '+ cGA);
                                                ^
Invalid group Address: 20/1/1
pi@raspberrypi:~ $





**bez. Musik:**
nein ich habe keine besonderen Einstellungen. EIN/AUS ist bei mir ein einfacher DPT1 Befehl und die homebridge liefert es auch dem entsprechend so weiter an den KNX Bus.

Aber tröste Dich..... mir geht es dafür bei anderen Befehlen so...z.B.: beim Rollladen öffnen kann ich nicht einfach sagen ""Hey Siri, Rollladen Essen öffnen" (wäre ja eigentlich Standard sollte man meinen :-) ) , sondern ich muss sagen "Hey Siri, Rollladen Essen AUFMACHEN".

**Comment by ChrisSthler** [comment]
mhm... ich tippe jetzt erstmal drauf das deine schreib Adresse SET 20/1/1 außerhalb des zulässigen Bereichs ist. zulässig ist 0/0/1 bis 15/7/255

mach da mal was anders rein und schau ob es geht.

**Comment by MrWichtig** [comment]
Hi Chris,

Goldrichtig! :-)

ich habe jetzt Testweise mal eine "fiktive" GA vergeben unter 15/x/x und siehe da es funkt!

warum dem so ist, frage ich mich trotzdem, da es erst seit Version 0.3.4 auftritt dass dem so ist.


dann wäre noch Rolladen Problem......fällt Dir dazu auch etwas ein? lt. Fehlermeldung schaut es nach einem Handler Problem aus, aber wie schon erwähnt verwende ich keine Handler?

> DPT: DPT5
================================
[1/3/2017, 12:46:26 PM] [homebridge-knx.KNX] CurrentPosition
[1/3/2017, 12:46:26 PM] [homebridge-knx.KNX] Adding characteristic...
[1/3/2017, 12:46:26 PM] [homebridge-knx.KNX] CharacteristicKNX.Constructor
---iterating--------------------
Type: CurrentPosition
Listen.0: 4/5/11
================================
INFO registerSingleGA 4/5/11
[1/3/2017, 12:46:26 PM] [homebridge-knx.KNX] PositionState
[1/3/2017, 12:46:26 PM] [homebridge-knx.KNX] Adding characteristic...
[1/3/2017, 12:46:26 PM] [homebridge-knx.KNX] CharacteristicKNX.Constructor
---iterating--------------------
Type: PositionState
================================
[1/3/2017, 12:46:26 PM] [homebridge-knx.KNX] Preparing KNXObjects: 1
/usr/lib/node_modules/homebridge-knx/lib/service-knx.js:173
                                throw new Error("Must not specify 'KNXObjects' property for default service handler in knx_config.json.");
                                ^

Error: Must not specify 'KNXObjects' property for default service handler in knx_config.json.
    at ServiceKNX.loadServiceData (/usr/lib/node_modules/homebridge-knx/lib/service-knx.js:173:11)
    at new ServiceKNX (/usr/lib/node_modules/homebridge-knx/lib/service-knx.js:52:25)
    at new KNXDevice (/usr/lib/node_modules/homebridge-knx/lib/knxdevice.js:101:23)
    at KNXPlatform.configure (/usr/lib/node_modules/homebridge-knx/index.js:194:23)
    at KNXPlatform.<anonymous> (/usr/lib/node_modules/homebridge-knx/index.js:88:9)
    at emitNone (events.js:86:13)
    at API.emit (events.js:185:7)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:93:13)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
pi@raspberrypi:~ $



**hier auch nochmal die config bei mir:**
(und wie schon erwähnt ist auch das Problem erst seit 0.3.4 Version homebridge)


>        {
            "DeviceName": "Rollladen Essen",
            "Services": [
                {
                    "ServiceType": "WindowCovering",
                    "ServiceName": "Rollladen Essen",
                    "Characteristics": [
                        {
                            "Type": "TargetPosition",
                            "Set": [
                                "4/4/0"
                            ],
                            "DPT": "DPT5"
                        },
                        {
                            "Type": "CurrentPosition",
                            "Listen": [
                                "4/5/0"
                            ]
                        },
                        {
                            "Type": "PositionState"
                        }
                    ],
                    "KNXObjects": [
                        {
                            "Type": "ShutterMove",
                            "Listen": "0/0/0",
                            "DPT": "DPT1"
                        }
                    ],
                    "KNXReadRequests": [
                        "4/4/0",
                        "4/5/0"
                    ],
                    "LocalConstants": {
                        "SomeVariable_notUsedHere": "SomeValue",
                        "OtherBlinds_notUsedHere": "OfficeShutter"
                    },
                    "subtype": "SUB_78d9fb9e-8447-4c70-882d-3272636c6517"
                }
            ],
            "UUID": "5bfb236f-f416-44c9-8b72-ef26659b3874"

**Comment by ChrisSthler** [comment]
sorry da bin wohl auch ich ein wenig dran schuld 
siehe hier https://github.com/snowdd1/homebridge-knx/issues/69

und zum Rollo wo und wie hast du deinen Handler gespeichert? 
weil er meckert ja Hier
`Error: Must not specify 'KNXObjects' property for default service handler in knx_config.json.`

Das KNXObjects nicht benannt ist und des ist normal im Handler gemacht. 

Ansonsten das auch mal einfach weglassen und nur Set und Listen Für Rollos nehmen.

```
 "DeviceName": "Rollladen Essen",
 "Services": [{
 		"ServiceType": "WindowCovering",
 		"ServiceName": "Rollladen Essen",
 		"Characteristics": [{
 					"Type": "TargetPosition",
 					"Set": [
 						"4/4/0"
 					],
 					"DPT": "DPT5"
 				}, {
 					"Type": "CurrentPosition",
 					"Listen": [
 						"4/5/0"
 					]
 				},
```
Also nur diesen teil nehmen :-)

**Comment by MrWichtig** [comment]
beim Issue Link wird man leider auf eine 404-Seite redirected....somit kann ich hier leider keine Infos entnehmen.

Ja, mit der Kurzversion funktioniert es jetzt auch......ich habe mir dazumals schon die Langvariante so gespeichert lassen im knx_config.json file, dass wenn ich weiterbastle nicht alles neu reinschreiben muss, da es in der Vorgängerversion ja auch funktionierte.

**@ChrisSthler**.....Danke für Deinen Support.....Innerhalb kurzer Zeit meine 2 Probleme gelöst, warum mich aber trotzdem interessieren würde was in Version 0.3.4 anders ist bzw sich zum knx_config.json anders verhält als die Vorgängerversionen?!
evtl. kann das **Raoul** mal bei Gelegenheit noch beantworten?!



bez. Musik nochmal....hast Du auch Squeezeboxen drann? Wenn ja was für eine Visu nutzt Du?

lg

**Comment by ChrisSthler** [comment]
Sorry mit dem link muss ich gleich mal guggen wieso das wieder nicht geht...
Der sollte aber jetzt gehen:
https://github.com/snowdd1/homebridge-knx/issues/69
bzw. hier die ganze Geschichte :-)
https://github.com/snowdd1/homebridge-knx-de/issues/26#issuecomment-265944912

Was in der zu Vorgänger Version geändert wurde findest du hier: https://github.com/snowdd1/homebridge-knx/blob/master/CHANGELOG.md

Helfe gerne wenn ich es so Leicht kann und selber mal was weis...

Und zur Musik Nein ich Habe Keine Squeezeboxen dran. Ich nutze für mein Multrioom Einen Yamaha RX-A Receiver Den Kann ich mit Verscheiden GAs EIN/AUS schalten oder ganz viele andere Sachen ändern. Und in Homebridge habe ich ihn auch nur als Switch deklariert. 
Deswegen gehe ich davon aus das Siri ein Problem mit dem Schlüssel Wort "Musik" hat.
Wenn ich (ist zustand) meine Musik, Lautsprecher nenne und Siri Sage "Schalte die Lautsprecher Küche Ein" macht sie es ja anstandslos.

MfG


PS: du hast mit deinem `> @Chris` Jemanden wild Fremdes damit Verlinkt :-) Aber Trotzdem Gerne geschehen 
solltest das wohl er bei Raoul machen. Dann wird er extra informiert

**Comment by ChrisSthler** [comment]
Aber du hast mich auf eine Idee gebracht. Muss ich heute Abend mal testen.

Du nutzt Für die Musik direkt ein Package für Squeezebox oder Bzw hast du "ServiceType als Speaker" angegeben ?
Vielleicht denkt Siri Soweit mit das es merkt das bei mir Ja keine  ServiceType als Lautsprecher bzw. was zum wiedergeben von Musik da ist und des wegen mich in die Musik-App umleitet.

**Comment by MrWichtig** [comment]
ich verwende den eibPort und da sind die Steuerelemente für Squeezebox schon integriert...man muss halt nur noch GA's dazu anlegen.

und beim Steuerelement EIN/AUS ist das einfach nur eine GA mit DPT1....mit dem Wort "Musik" habe ich noch nie Probleme gehabt....hatte von Anfang an funktioniert bei mir.

ich habe eigentlich immer einen Service Typ "Switch" gemacht, da das bisher immer funktioniert hatte.

im folgenden Beitrag habe ich auch schon Service Typ "Speaker" ausprobiert. hier hat mir auch Raoul den Tipp gegeben, da es aber noch relativ neu ist gibt es auch wenig Erfahrungswerte damit.

ich selbst habe "Speaker" ausprobiert und EIN/AUS funktioniert genauso gut. Bei der Lautstärke bin ich aber dann auch gescheitert, da wiederum Handler benötigt werden und ich hierbei sehr wenig Erfahrung habe wie man das "Handler basteln" angeht. somit gebe ich mich noch mit EIN/AUS zufrieden :-)

**Comment by ChrisSthler** [comment]
also ich habe zwar keinen eibPort, aber einen IP-Control leider hatte ich nur Probleme damit ist mittleweile der 4 oder 5 deswegen nutze ich nur noch sehr wenig... Aber des SB-Control habe ich auch noch nicht so genutzt, nur mal zum testen.

Mein AVR hat auch unter anderen eine GA (DPT1) die EIN/AUS auch dazu nutze die unterschiedlichen Zonen steuern.

noch eine Frage enden deine Raum Bezeichnung auf "Zimmer"? also sagst du:
"Schalte Musik Arbeitszimmer" Ein (sagt ich das Versteht Siri Das Wort Musik nicht...)
Oder
"Schalte Musik Arbeiten Ein" (sage ich aber Das leitet mich Siri auf Die Musik-App um)

**Comment by MrWichtig** [comment]
hi,

meine Bezeichnungen habe ich immer ohne "ZIMMER" gemacht um alles kurz zu halten ;-)

z.B.:
"Schalte Musik Essen EIN"
"Schalte Musik Wohnen EIN"
"Schalte Musik Terrasse EIN"

usw....



....in APP (z.B.: Eve) kannst Du EIN/AUS schalten?

**Comment by ChrisSthler** [comment]
okay.... aber jetzt gehen mir langsam echt die Ideen aus was ich falsch mache.

**Comment by MrWichtig** [comment]
hast Du das ganze jetzt mit Service Typ "Switch" oder "Speaker" gemacht?

ich erinnere mich nämlich düster daran, dass ich das auch kurzzeitig mal hatte, dass Siri die Itunes APP Musik geöffnet hat.
Probier einmal wenn möglich (rein zum testen meine Namensgebung....also z.B. "Musik Wohnen) für Deinen Lautsprecher

**Comment by ChrisSthler** [comment]
Habe mittlerweile beides drinnen und Probiert. Problem Besteht bei beiden Versionen.

**Comment by ChrisSthler** [comment]
Sobald das Schlüssel Wort "Musik" vorkommt schickt er mich entweder in die Musik-App oder kennt es nicht. Mit dem Wort "Lautsprecher" geht es.
also 
"Schalte Musik Wohnen (oder Wohnzimmer) EIN/AUS " --> geht nicht.
aber
"Schalte Lautsprecher Wohnen (oder Wohnzimmer) EIN/AUS " --> geht.

egal ob ich sie als Service Typ "Switch" oder "Speaker" deklariere.
werde heute Abend nochmal wenig alle Kombinationen testen.

**Comment by MrWichtig** [comment]
hast Du "Device Name" und "Service Name" auch gleich benannt?
normalerweise sollte das ja keine Rolle spielen da ja sowieso nur auf Service Name hören sollte aber man ist ja gerade beim Troubleshooten :-)....da muss man alles in betracht ziehen.

bei mir sind beide gleich benannt....

**Comment by ChrisSthler** [comment]
NEIN habe ich leider nicht.
Bin Über die 100 (99)Geräte. Deswegen Für jeden Raum/Bereich nur den "Device Name" und dann die Aktoren/Sensoren GAs mit dem "Service Name" beschriftet.

Kann ich aber heute Abend auch mal gerne mit einbauen und testen. Habe aktuelle nur beschränkt zugriff aus System.

**Comment by snowdd1** [comment]
Guten Abend , ihr wart ja ganz schön aktiv während meines Urlaubs.  
Was ist denn jetzt eigentlich noch offen?  
Das Problem mit den Adressen größer als 15/7/255 ist bekannt, und ich habe versucht das bei `Node-eibd` zu adressieren. Sobald das Paket das unterstützt, kann ich die Beschränkung wieder entfernen.  
Mit dem *Musik* -Schlüsselwort für Siri habe ich nichts zu tun :-)

**Comment by MrWichtig** [comment]
Hi Raoul,

Ja, aus meiner Sicht wäre nur die Adressierung noch offen. hat mich seit dem Update schwer zu schaffen gemacht, da nichts mehr ging, aber Dank Chris Hilfe konnte ich dieses Problem auch identifizieren.
hoffen wir mal, dass es hier bald Rückmeldung gibt......bisher habe ich alles über 15/x/x weggelassen, da ich bei einer Umstellung der GA's schon einiges angreifen muss.

Bez. "Wortlaut-MUSIK" bin ich mir nicht sicher ob Chris das in den Griff bekommen hat, eine generelle Funktion sollte jedenfalls möglich sein, da es bei mir auch so funktioniert, wir aber keinen Anhaltspunkt noch gefunden haben warum?!

na dann noch ein herzliches Welcome Back! :-)

**Comment by ChrisSthler** [comment]
hey ihr...
also ich konnte leider noch nicht weiter testen woran es bei mir scheitert.
aber vielleicht finden wir ja noch paar weitere die mit testen könnten.

Ansonsten läuft es ja bei mir mit dem Schlüsselwort "Lautsprecher" bzw. über den Aufruf von bestimmten Szenen.

**Comment by MrWichtig** [comment]
@snowdd1 
nachdem "andreek" das Thema der GA's geschlossen hat musst Du jetzt auch noch etwas anpassen oder nicht mehr?

wenn ja wird das in der Version 0.3.4 angepasst werden od. wird es eine neue z.B.: 0.3.5 geben?

so wie ich es verstanden habe sollte der Range ja bis 31/x/x möglich sein?!

lg

**Comment by snowdd1** [comment]
Doch muss ich. Werde ich die nächsten tage machen.

**Comment by MrWichtig** [comment]
Perfekt ! :-)

Dankeschön!

**Comment by MrWichtig** [comment]
Alles funkt wieder wie gehabt seit 0.3.5 Update! :-)
THX!

**Comment by snowdd1** [comment]
Nein, besser, denn nun können Adressen über `15/` auch empfangen werden, nicht nur gesendet!

**Comment by snowdd1** [comment]
Dazu muss von node-eibd die 0.3.6 installiert sein.

**Comment by snowdd1** [comment]
Und noch besser, das ist eigentlich das beste an der ganzen Geschichte, ist das Node-eibd jetzt die hohen Adressen nicht mehr falsch zurückgibt, das hätte nämlich auch schlimme Folgen haben können. Stell dir vor, dein Licht hat 17/1/1 und Deine Alarmanlage hat auf 1/1/1 den Alarm - mit der alten Version wäre 17/1/1 als 1/1/1 angekommen und statt des "Licht ist an!" wäre ein "Alarm ausgelöst" in HomeKit angekommen.

**Comment by MrWichtig** [comment]
kann man node-eibd auch updaten oder muss man das nochmals normal installieren mit folgenden Befehlen?

`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`

`sudo apt-get install -y nodejs libavahi-compat-libdnssd-dev git-core build-essential cdbs autoconf`

**Comment by snowdd1** [comment]
Nee, 
das ist ja auch ein node paket  (https://www.npmjs.com/package/eibd), kein Binäres  
`npm update eibd` bzw.  
`sudo npm update -g eibd` wenn du es global installiert hast.

**Comment by MrWichtig** [comment]
wenn ich das Update mit

`sudo npm update -g eibd`

...mache bekomme ich die Version v6.9.2 angezeigt und nicht 0.3.6 ?  Verwechsle ich da etwas oder reden wir da eh vom gleichen?

**Comment by snowdd1** [comment]
Kannst du mal den Output der Console einfügen? Das sieht aus wie die node-version.

```shell
pi@homebridge-dev:~/node_modules $ node -v
v6.9.2
```

Was blöd ist, ist das die Abhängigkeiten wohl nicht so toll aufgelöst werden, wie ich mir das gedacht hatte. Hier mal auf einem alten Image:  
```shell
pi@homebridge-dev:~/node_modules $ npm update homebridge-knx
- ms@0.7.2 node_modules/homebridge-knx/node_modules/debug/node_modules/ms
- debug@2.3.2 node_modules/homebridge-knx/node_modules/debug
- eibd@0.3.5 node_modules/homebridge-knx/node_modules/eibd
/home/pi
└── homebridge-knx@0.3.5

npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
pi@homebridge-dev:
```
Wie man schön sieht, scheint die neue Version von `eibd` nicht installiert worden zu sein (immer noch 0.3.5 nach dem Output) zu urteilen.  
Allerdings zeigt
```bash
pi@homebridge-dev:~/node_modules $ npm list eibd
/home/pi
└─┬ homebridge-knx@0.3.5
  └── eibd@0.3.6

pi@homebridge-dev:~/node_modules $
```
schon die aktuelle 0.3.6 für `eibd`. Merkwürdig. *Ich habe keine globale installation, sondern user/verzeichnisbasiert daher bei mir kein `-g`*

**Comment by MrWichtig** [comment]
Hi,


mehr "Auflösung habe ich nicht was mir angezeigt wird:

![image](https://cloud.githubusercontent.com/assets/20240146/22184640/559aac96-e0d6-11e6-83ee-7d1ba770d38d.png)

**Comment by snowdd1** [comment]
ok, `using node@v6.9.2` das ist nur die node-Version.  

Guck mal mit `npm list -g eibd` was da angezeigt wird.

**Comment by MrWichtig** [comment]
@snowdd1 

ja da wird es richtig angezeigt :-)

...somit lassen wir es gut sein!

Danke nochmals!

![image](https://cloud.githubusercontent.com/assets/20240146/22220626/ae8ee3c4-e1af-11e6-8268-de96b2da28ba.png)
