### ISSUE TITLE
Rollladen Steuerung

### ISSUE THREAD

**Issue by vanadium12** [snowdd1/homebridge-knx-de#36]
Zunächst, ich bin von homebridge knx begeistert. Funktioniert fantastisch mit unserem Gira  Bussystem. 
Eine Kleinigkeit bekomme ich aber nicht hin. Sowohl der GiraJalousieActuator Handler als auch der abgewandelte Tilt Handler führen dazu, dass unsere Raffstore (mit Lamellen) bei Target Value 100% offen, nach ca 10 Sekunden die per ETS am Gira Aktor festgelegte Lamellenfahrtzeit (ca 2 Sekunden) wieder nach unten fährt. 
Beim Tilt Handler geht es (wenn ich richtig gesehen habe) entsprechend um die voreingestellte Lamellen Neigung wieder nach unten. Das bedeutet im HomeKit ständig 96% offene Jalousien statt ganz geöffnete.
 Wenn ich per ETS die Lamellenfahrtzeit auf 0 Sek stelle , gibt es das Problem nicht. Die  Definition der Lamellenfahrtzeit brauche ich allerdings für die automatische Beschattung im Sommer mit Lamellennachführung, also keine Lösung für mein Problem.
Bei unseren Jalousien (Fa Josko) wird die Lamellenposition mit dem selben Motor wie die Jalousieöffnung gesteuert. Bei Aufwärtsfahrt gehen die Lamellen auf, bei Abwärtsfahrt gehen sie zu. Nehme an das ist Standard bei den meisten Jalousien mit Lamellen.
 Gibt es eine einfache Möglichkeit per Handler bei Target 100% Öffnung die Nachjustierung der Lamellen auf die zuvor angefahrene Neigung zu unterbinden ?

Bin über jeden Hinweis dankbar.
Viele Grüße, Tom

**Comment by snowdd1** [comment]
Hallo Tom, ich wüsste nicht wie. Es wird ja 100% (bzw. 0%) per KNX an den Stellmotor (bzw den Aktor) geschickt. Was sollte man denn hinterherschicken, um die im Aktor definierte Aktion zu unterbinden? Hat der noch eine Adresse für die Lamellenverstellung? Da ich aber so etwas nicht habe, ist @giase82 vielleicht ein kompetenterer Ansprechpartner?!  
Gruß
Raoul

**Comment by vanadium12** [comment]
Hallo Raoul, vielen Dank für die Antwort. Ja es gibt separate Adressen für die Lamellenposition (target Position und Pos.Rückmeldung). Der Aktor ist meines Wissens ein Gira 216100. Ich habe es vorerst so gelöst, dass ich im Array für die Jalousie Target Position auch die Adresse der Lamellen Position hinzufüge. Raffstore oben = Lamellen ganz offen, Raffstore unten = Lamellen ganz zu. Ist zwar nicht die eleganteste Lösung aber klappt in der Praxis gut, da wir die Jalosien fast nie in einer anderen Position als 0% und 100% haben. 
So klappt auch die Beschattungssteuerung wieder und der Aktor kann bei entsprechendem Wettergrenzwert die Jalousien schließen und Lamellennachführung machen. Bin aber gespannt ob @giase82 dazu noch eine Idee hat. 
Viele Grüße, Tom

**Comment by giase82** [comment]
Hi Ihr,

Ich bin mir nicht sicher, ob ich das Problem richtig verstehe, aber kann es sein dass das ein Problem mit HomeKit-100% = Geöffnet und KNX-100% = Geschlossen ist? Du müsstest dann dementsprechend den invertierten Wert nehmen.... Ich erinnere mich dunkel dass da mal was war.

//Christof

**Comment by vanadium12** [comment]
Danke euch beiden für die Antworten. Nein @giase82 leider nicht. Es scheint entweder im Gira Aktor oder im HomeKit versteckt zu sein, die lamellenstellung nach der Jalousiefahrt wiederherzustellen. Per tastsensoren schalte ich nur eine 0 oder 1 für auf und zu (da gab es das Problem nie) per HomeKit wird % Jalousieposition an KNX übergeben. Das Dilemma ist nun dass für eine vollständige Öffnung der Jalousie die Lamellen ganz offen sein müssen. Wenn ich nun bei geschlossenen Jalousien (mit geschlossenen Lamellen) den Befehl zur Öffnung schicke klappt das zunächst auch. 15 Sekunden nachdem die Jalousien offen sind, erinnert sich das System aber, dass die Lamellen zuvor geschlossen waren und fährt die Jalousie um 2 Sekunden (das ist die eingestellte Lamellenfahrtzeit im ETS) nach unten um den vorherigen LamellenZustand wiederherzustellen. Ich habe daher in den KNX Adressen Array für die % Jalousieöffnung im Config file auch die % Lamellenöffnung einfach hunten dran hinzugefügt wie oben beschrieben. Damit ist das Thema für mich gelöst. Ist zwar nicht sehr elegant aber solange es klappt ;)

**Comment by giase82** [comment]
Ach jetzt verstehe ich. Ja, mein Berker Aktoren reagieren auch so. Wenn ich ihnen eine 0 oder eins für auf und zu gebe, fahren auch die Lamellen ganz auf oder zu. Wenn man jetzt aber die Jalousie-Position per %-Wert übergibt, gibt es das "feature", dass sich der Aktor die Lamellenposition merkt. Das kann natürlich auch durchaus so gewollt sein. 
Mit deiner Lösung ist halt z.B. bei 50% Jalousieposition auch die Lamelle bei 50%. Wenn das für dich ok ist passts.
Man könnte natürlich auch das Plugin anpassen, damit das bei 0 oder 100% nicht die %-Werte übergibt, sondern die 0 oder 1 für auf/zu. Wäre aber ein bisschen Aufwand...

//Christof
