### ISSUE TITLE
homebridge mit Gira- oder EIBMarkt-KNX/IP-Gateway

### ISSUE THREAD

**Issue by kustus** [snowdd1/homebridge-knx-de#37]
Ich habe in Hyper-V ein Ubuntu 16.04 LTS und darin homebridge installiert und konfiguriert. Alles gut soweit. Ich sehe es auch im iPhone und kann ein Haus einrichten. ABER: keine Signale werden auf den KNX-Bus gelesen oder geschrieben, obwohl im Terminal die Klicks mit der richtigen Bus-Adresse bei Klick angezeigt werden. Ich verwende NICHT KNXD, sondern einen bereits vorhandenen EIBMarkt IP Gateway (Hutschiene). In der knx_config.json habe ich dieses KNX/IP Gateway so angegeben, wie die ETS eine Verbindung da hin korrekt aufbaut (Beispiel: "knxd_IP": "192.168.178.10", "knxd_port": "3671"). Das Gateway ist bei den Tests auch frei und nicht von ETS blockiert.

Kann einer helfen? Bin 1 cm vor dem Ziel, aber es schreibt nix auf den Bus. Da ich schon einen Server mit Hyper-V habe, brauche ich nicht noch zusätzlich eine Pi-Hardware mit IP-Gateway, nur homebridge wird benötigt.

**Comment by snowdd1** [comment]
Hallo @kustus ,  
homebridge-knx kann **nur** über den knxd kommunizieren. Der knxd seinerseits spricht aber gerne mit deinem Gateway. Also in ubuntu noch den knxd installieren - die Standardinstallation ohne Anpassung der Parameter sollte bei Dir funktionieren, wenn dein Gateway auch multicast spricht.
Gruß
Raoul

**Comment by kustus** [comment]
Hallo @snowdd1 ,
perfekt! Ich habs hin bekommen mit deinem Hinweis. Die erste Lampe kann ich ein- und ausschalten, auch über Siri.Danke für die schnelle Info, ich hatte einfach knxd falsch als reines USB-Gateway interpretiert. Danke danke danke.
Gruß
Jörg
