### ISSUE TITLE
Update homebridge-knx 0.3.8

### ISSUE THREAD

**Issue by MrWichtig** [snowdd1/homebridge-knx-de#39]
Hi,

ich habe gesehen, dass es mittlerweile auch schon wieder ein homebridge-knx update gibt.
ist das auch schon released um es global zu installieren?

wenn ich mit :
`sudo npm -g update homebridge-knx`

update....steht bei mir immer noch 0.3.5 ?

**Comment by snowdd1** [comment]
Scheint Probleme mit dem update zu geben. Drüber-Installieren hilft.  
Vielleicht auch die Reihenfolge der Parameter wichtig?  
"update" "global" statt "global" "update"?  
Versuch mal `sudo npm update -g homebridge-knx`.  
Ansonsten hilft `sudo npm install -g homebridge-knx`  

Siehe https://github.com/snowdd1/homebridge-knx/issues/82

**Comment by MrWichtig** [comment]
Danke!

mit Neu Install hats funktioniert.. :-)
