### ISSUE TITLE
Siri Befehle (Apple Watch vs. Iphone) 

### ISSUE THREAD

**Issue by MrWichtig** [snowdd1/homebridge-knx-de#40]
Hi,

ich habe beides in Verwendung und seit dem letzten Apple Watch OS Update (3.1.3) werden nicht mehr alle Befehle über Siri ausgeführt.
hier bekomme ich immer des öfteren die Rückmeldung von Siri "Tut mir leid, das konnte ich nicht tun"...etc.....etc..

über das Iphone direkt mit Siri funktionieren jedoch alle Befehle!

ich dachte immer, dass wenn ich über die Apple Watch Siri anspreche diese sowieso immer über das Iphone kommuniziert?!

ist dem nicht so?

**Comment by snowdd1** [comment]
Das habe ich, seit ich die Watch habe. Ein zweiter Versuch hilft meistens.  
"Siri, öffne die Garage" - *das kann ich nicht tun*.  
"Siri, öffne die Garage!" - *dein Wunsch ist mir Befehl...*

😒

**Comment by MrWichtig** [comment]
dürfte also doch irgendwie ein Eigenleben ohne Iphone führen :-)

bei mir wirkt es sich anders aus.......hat früher immer auf Anhieb funktioniert und nun überhaupt nicht mehr!....auch nach mehrmaligen Probieren....

ok...mal abwarten  und Tee trinken bis mal wieder ein Update kommt :-)

**Comment by snowdd1** [comment]
Ich habe es bisher drauf geschoben dass die Blauzahnverhindung noch mal einen zusätzlichen Lag und ggf. Paketverluste mitgebracht hat.

**Comment by snowdd1** [comment]
Verbindung, nicht Verhinderung! Aber vielleicht hat AutoCorrect auch recht!

**Comment by MrWichtig** [comment]
:-)
jaja....so viel Technik die mitspielt :-)
