### ISSUE TITLE
Problem mit Rollosteuerung

### ISSUE THREAD

**Issue by hebe2k** [snowdd1/homebridge-knx-de#42]
Hi @snowdd1,

ich habe Probleme mit der Rollosteuerung.

Vorab ein paar Infos:
1. Es werden Rollos gesteuert, keine Jalousien.
2. Aktor ist ein Gira Rollo-Aktor
3. Die Positions-Objekte in der ETS sind mit DPT 5.001 (0..100%) konfiguriert.

Ich habe sowohl den Standard-Handler versucht als auch den Gira spezifischen Handler (https://github.com/snowdd1/homebridge-knx-de/wiki/Handler:-GiraJalousieActuator).
Bei dem einen geht die Prozentsteuerung und dafür sind Öffnen und Schließen vertauscht, bei dem anderen funktioniert Öffnen und Schließen korrekt, dafür ist die Prozentsteuerung falsch.

# GiraJalousieActuator

**knx_config.json**

```
        {
            "DeviceName": "Büro Rollo",
            "Services": [
                {
                    "ServiceType": "WindowCovering",
                    "Handler": "GiraJalousieActuator",
                    "ServiceName": "Büro Rollo",
                    "Characteristics": [
                        {
                            "Type": "TargetPosition",
                            "Set": [
                                "3/4/10"
                            ],
                            "DPT": "DPT5.001"
                        },
                        {
                            "Type": "CurrentPosition",
                            "Listen": [
                                "3/3/10"
                            ]
                        },
                        {
                            "Type": "PositionState"
                        }
                    ],
                    "KNXObjects": [
                        {
                            "Type": "ShutterMove",
                            "Listen": "3/1/10",
                            "DPT": "DPT1"
                        }
                    ],
                    "KNXReadRequests": [
                        "3/3/10"
                    ],
                    "LocalConstants": {
                        "TimeOutSecs": 60
                    },
                    "subtype": "SUB_10c269b5-d2a6-4750-b2f9-b7b4d27b72af"
                }
            ],
            "UUID": "24fa8c68-245c-4c58-9ff8-57a42a097ba7"
        },
```

**Vorteil:**

- Öffne das Rollo im Büro => öffnet das Rollo
- Schließe das Rollo im Büro => schließt das Rollo
	
**Nachteil:**
Steuerung über %-Werte funktioniert nicht korrekt, die Werte werden vertauscht.
		Beispiele:
			1. Stelle das Rollo im Büro auf 20% => es wird auf 80% gestellt
			2. Stelle das Rollo im Büro auf 30% => es wird auf 70% gestellt

# Alternative die default Rollo Config

```
{
    "DeviceName": "Büro Rollo",
    "Services": [
        {
            "ServiceType": "WindowCovering",
            "ServiceName": "Büro Rollo",
            "Characteristics": [
                {
                    "Type": "TargetPosition",
                    "Set": [
                        "3/4/10"
                    ],
                    "DPT": "DPT5.001"
                },
                {
                    "Type": "CurrentPosition",
                    "Listen": [
                        "3/3/10"
                    ]
                },
                {
                    "Type": "PositionState",
                    "Listen": [
                        "3/1/10"
                    ]
                }
            ],
            "KNXReadRequests": [
                "3/3/10"
            ],
            "LocalConstants": {
                "TimeOutSecs": 23
            },
                    "subtype": "SUB_10c269b5-d2a6-4750-b2f9-b7b4d27b72af"
                }
            ],
            "UUID": "24fa8c68-245c-4c58-9ff8-57a42a097ba7"
},
```

**Vorteil:**
Steuerung über %-Werte funktioniert problemlos.

**Nachteil:**
**Sprach-Befehl:** Öffne das Rollo im Büro
**Reaktion:** schließt das Rollo

**Sprach-Befehl:** Schließe das Rollo im Büro
**Reaktion:** öffnet das Rollo

Gruß,
Henning

**Comment by snowdd1** [comment]
Hallo Henning,
muss ich mir ansehen. Ich verwende auch den GiraJalousieActuator, habe aber seit Wochen nur "öffne" oder "schließe" zu Siri gesagt, oder auf der Watch die % eingestellt, und da geht es. 
Du hast die % über Siri eingestellt?
Gruß

**Comment by hebe2k** [comment]
Hallo Raoul,

ja den Befehl habe ich über Siri auf einem iPhone 6 gesprochen.
iOS Version 10.2.1.

Anbei noch die Logs vom Einsatz des GiraJalousieActuator Handlers und dem Siri-Befehl "Stelle das Rollo im Büro auf 20%":

### homebridge-knx log:
```
[3/22/2017, 11:28:11 AM] [homebridge-knx.KNX] GiraJalousieActuator->customServiceAPI.getValue(CurrentPosition)
[3/22/2017, 11:28:11 AM] [homebridge-knx.KNX] Returning HomeKitValue
[3/22/2017, 11:28:11 AM] [homebridge-knx.KNX] Returning HomeKitValue of 0
[3/22/2017, 11:28:11 AM] [homebridge-knx.KNX] GiraJalousieActuator->customServiceAPI.setValue(PositionState,1)
[3/22/2017, 11:28:11 AM] [homebridge-knx.KNX] Value changed, updating homebridge
[3/22/2017, 11:28:11 AM] [homebridge-knx.KNX] exiting writeValueHK()
[3/22/2017, 11:28:11 AM] [homebridge-knx.KNX] GiraJalousieActuator->customServiceAPI.knxWrite(TargetPosition,204,DPT5)
[3/22/2017, 11:28:11 AM] [homebridge-knx.KNX] DEBUG got dest=7178
[3/22/2017, 11:28:18 AM] [homebridge-knx.KNX] GiraJalousieActuator->customServiceAPI.setValue(CurrentPosition,20)
[3/22/2017, 11:28:18 AM] [homebridge-knx.KNX] Value changed, updating homebridge
[3/22/2017, 11:28:18 AM] [homebridge-knx.KNX] exiting writeValueHK()
[3/22/2017, 11:28:18 AM] [homebridge-knx.KNX] GiraJalousieActuator->customServiceAPI.setValue(PositionState,2)
[3/22/2017, 11:28:18 AM] [homebridge-knx.KNX] Value changed, updating homebridge
[3/22/2017, 11:28:18 AM] [homebridge-knx.KNX] exiting writeValueHK()
```

### ETS Gruppenmonitor:

![image](https://cloud.githubusercontent.com/assets/7340754/24199598/840fecd2-0f0a-11e7-88d3-26ac1b646ee7.png)


Gruß,
Henning

**Comment by snowdd1** [comment]
Hallo Henning, das ist aber normal. Für HomeKit ist 100% offen, für KNX ist 100% geschlossen, also ist 20% in Hoemkit 80% in knx.

**Comment by hebe2k** [comment]
Hallo Raoul,

ist der GiraJalousieActuator Handler dann nur um offen und geschlossen zu tauschen oder warum hast du den geschrieben?
Dann macht der für mich keinen Sinn, dann bleibe ich lieber bei dem default Handler und verwende für offen einfach 0% und für geschlossen 100%, also als Siri-Spracheingabe-Befehl.

Warum funktioniert die %-Steuerung denn dann mit dem default Handler korrekt, wenn ich da 20% sage, dann kommen auch bei KNX 20% an.
Ich hatte die Hoffnung die Vorteile beider Handler vereinen zu können.

Gruß,
Henning

**Comment by snowdd1** [comment]
Der Handler erledigt die folgenden Dinge: 
- Berechnung der %-Werte zwischen HomeKit und KNX (jeweils 100-x%)
- Setzen der richtigen "PositionState"s (1 = fährt hoch, 0=fährt runter, 2 = gestoppt)  
    Dies wird zum Beispiel von der Elagto Eve App benutzt um zu zeigen ob der Rollo gerade fährt. Apple's Home App verwendet leider einen Vergleich von Zielwert und Istwert, daher sind die folgenden Dinge notwendig:  
- Setzen des Zielwertes während der Bewegung  
      es gibt ja auch noch physische Taster im Raum - wenn du dort "abwärts/schließen" auslöst, wird während des Fahrens der Zielwert auf 0% (ganz geschlossen) in HomeKit gesetzt, so zeigt die Home App dann an, dass der Rollo gerade schließt
- Setzen des Zielwerts nach Beendigung der Fahrt 
    Beendest Du die Fahrt bevor der Rollo ganz unten angekommen ist, sendet der Gira Jalousie-Aktor die erreichte Position. Diese wird vom Handler als Ziel- *und* Ist-Wert an HomeKit geschickt (natürlich umgerechnet), damit die Home App nicht glaubt, dass dein Rollo sein Ziel nicht erreicht hätte und noch fahren müsste.  
- Falls die Bewegung länger als die maximale eingestellte Fahrtzeit dauert, wird ebenfalls der Zielwert=Istwert gesetzt, da davon auszugehen ist, dass lediglich ein Telegramm nicht angekommen ist, und HomeKit aufhören kann die Jalousie/Rollo als "in Bewegung" anzuzeigen.

Wenn Du das alles nicht brauchst, kannst Du natürlich auch einfach direkt die Implementierung von Apple benutzen.

**Comment by snowdd1** [comment]
> Warum funktioniert die %-Steuerung denn dann mit dem default Handler *korrekt*, wenn ich da 20% sage, dann kommen auch bei KNX 20% an.

Das ist eben nicht korrekt. HomeKit definiert einen Prozent-Offen-Wert (0% = geschlossen, 100% = ganz geöffnet) und KNX einen Prozent-Geschlossen-Wert (0% = geöffnet, 100% ganz geschlossen)

Wenn Du also Siri 20% sagst, dann ist das für HomeKit fast geschlossen (und wird auch so angezeigt, z.B. über den Slider auf der Watch oder in der iOS App). Wenn es dich nicht stört, dass unten in der App oben am Fenster ist, brauchst Du den Tausch nicht mitzumachen. Sagst Du also zu Siri: "Stelle das Fensterrollo *(bzw. Name des Services)* auf 100%" ist das identisch zu "öffne das Fensterrollo *(bzw. Name des Services)*"
