### ISSUE TITLE
Wie ist das richtige Vorgehen bei Änderungen an der knx_config.json?

### ISSUE THREAD

**Issue by flaute** [snowdd1/homebridge-knx-de#43]
Hallo zusammen!

Ich habe eine ziemlich große KNX-Installation (Wohnhaus mit Einliegerwohnung, ca. 80 Aktoren und ca. 20 Jalousien/Rolläden, ca. 10 Temperatur-Sensoren) mit `homebridge-knx` auf einem Raspberry PI 3. Läuft alles wirklich perfekt und stabil, ich bin begeistert! Vielen Dank an alle, die an den entsprechenden Projekten mitgewirkt haben - vor allem natürlich an @snowdd1 .

Ich habe eine Frage zum richtigen Vorgehen bei Änderungen an der `knx_config.json`:

Die `knx_config.json` ist natürlich ziemlich groß, daher habe ich mir einen Generator dafür geschrieben. Wenn ich jetzt einen weiteren Aktor hinzufügen will, generiere ich die `knx_config.json` neu und spiele sie in den Raspberry PI 3 ein. Danach ein Neustart - aber was dann? Ich muss immer in der "Home"-App das ganze Haus löschen, und dann das neue Homebridge-Device hinzufügen. Damit sind natürlich alle Änderungen / Umbenennungen und vor allem Raum-Sortierungen in der App wieder gelöscht...

Gibt es einen Weg, die `knx_config.json` anzupassen, und die Änderungen direkt in der "Home"-App sichtbar zu machen, ohne das ganze Haus löschen zu müssen? Vielleicht habe ich auch das mit dem Caching noch nicht richtig verstanden? Bin für jeden Hinweis dankbar.

Hier meine `knx_config.json`:
https://gist.github.com/flaute/3608372798c514d0dbcc6c0affe52c2e
Es ist eine `Hombridge`, mit einem `Device` je Raum und vielen `Services` je `Device`.

Danke
Gruß
flaute

**Comment by snowdd1** [comment]
Hallo @flaute ,
die *knx_config.json* wird beim ersten Start, bzw. beim Einlesen neuer Devices, vom Plug-In geändert. Siehe [Anleitung](https://github.com/snowdd1/homebridge-knx/blob/master/knx_config.json.md#uuid-and-subtype).

Immer wenn Du die Datei austauschst, werden alle Geräte als *neu* erkannt, da sie keine passende **UUID** haben (oder bei den Services den **subtype**). 

Verhindern kannst Du das nur, in dem du die *knx_config.json* von Deinem Raspberry als Basis für die überarbeitete Version verwendest. **ODER**: du erzeugst selbst entsprechende Kennungen, die du in deinem Generator hinterlegst, so dass sie jedes Mal wieder verwendet werden. Allerdings ist es leider erforderlich, dass beim Hinzufügen von Services das Gerät neu zu HomeKit hinzugefügt wird. Homebridge unterstützt noch kein hinzufügen von Services zu bestehendes Geräten.

Gruß  
Raoul

**Comment by flaute** [comment]
Ok, soweit nachvollziehbar.

Wenn ich daraus den Umkehrschluss ziehe, sollte es also möglich sein in der vorhandenen knx_config.json die unveränderten Geräte (Devices) mit ihren UUIDs zu belassen, aber ein Gerät (Device) - was bei mir einem Raum entspricht - zu entfernen und durch einen neues Device (ohne UUID) zu ersetzen, in dem dann auch der jeweilige neue Service (z.B. ein weiterer Aktor/Lightbulb) vorhanden ist.

Dann müsste in der Home-App nur das eine, neue Device im Standard-Raum erscheinen, und ich könnte diese Services der Raumes wieder 'in einem Rutsch' in den korrekten Raum verschieben, da immer alle Services gemeinsam verschoben werden.

Ich denke, das muss ich wohl mal probieren... Oder versteht das noch einer so?!?

**Comment by snowdd1** [comment]
Richtig! So mache ich es auch - nur habe ich keinen Generator, sondern habe die Zimmer am Anfang einfach kopiert und die GAs ausgetauscht.

**Comment by Ralle82** [comment]
Moin Flaute!
Ich stehe gerade vor dem gleichen Problem: ca. 100 Knx devices und habe keinen Generator . Würdest du deinen ggf zur Verfügung stellen?
