### ISSUE TITLE
Waveline Fenster Sensor einbinden...

### ISSUE THREAD

**Issue by ctschach** [snowdd1/homebridge-knx-de#45]
Ich glaube ich brauche mal eine Initialzündung :-)

Mir ist klar, dass ich unter "addins" meine eigene Anpassungen machen kann. Ich habe mir die Sources per git geladen, aber wie geht's dann weiter? Datei hinzufügen, aber die wird es dann installiert?

Prinzipiell geht es darum, dass ich die Waveline Fenstersensoren nutze - diese liefern DPT5.001 und zwar "0x00" für geschlossen, "0x80" für Kipp und "0xFF" für geöffnet.

Diese will ich nun gerne auf den ServiceType "Window" anbilden. Also bei "0x00" die Werte für CurrentPosition, TargetPosition und PositionState auf "0" setzen. Bei 0x80 dann Current und Target auf 50% sowie PositionState auf "1". Bei 0xFF dann beides auf 100% sowie PositionState auf "1".

Das umzusetzen sollte mir noch gelingen, wenn ich nur wüsste, die ich es dann einbinde.

**Comment by snowdd1** [comment]
Der Dateiname wird als Händler in die knx_config.json eingetragen, that's it.

**Comment by ctschach** [comment]
Okay, hab's irgendwie geschafft. Habe mal ein Pull Request gesendet.

Einziges Problem was ich noch habe. Die Fenstersensoren erlauben ja nicht, den Wert zu setzen. Demnach setze ich die TargetPosition bei Wertänderung wieder zurück auf die CurrentPosition. Das wird läuft auch in der Console, wird aber im Client auf dem iPhone nicht aktualisiert.

**Comment by snowdd1** [comment]
Referenz: https://github.com/snowdd1/homebridge-knx/pull/97

**Comment by snowdd1** [comment]
Sehe erst mal keinen Fehler. Mal sehen ob ich das am WE nachstellen kann, ohne die HW.

**Comment by ctschach** [comment]
Der Vorteil gegenüber Kontaktsensoren ist, dass man bei den Service "Window" eine Push Benachrichtigung bekommt, was ich ganz nett finde.

**Comment by snowdd1** [comment]
Kannst Du bei Kontaktsensor auch aktivieren. Nutze ich auch für "virtuelle Kontakte" wie "alles verschlossen" - vermeidet die Diskussion mit der Ehefrau auf dem Weg in den Urlaub...!

**Comment by snowdd1** [comment]
Window ist eigentlich aktiv, ich habe ein Velux-Dachfenster auf 4m Griffhöhe im Dach mit Motorantrieb, das ich mit Window-Service steuern kann - aber nie tu, weil es am Homeserver hängt und automatisch lüftet...

**Comment by ctschach** [comment]
Okay, aber bei Windows kann ich ihn halt auch auf 50% setzen, wenn es gekippt ist. Das erkennt der Waveline Sensor. Ist ja ein Sensor, den man auf den Fensterknauf setzt
