### ISSUE TITLE
LightBulb und Brightness Value geht immer auf 100%

### ISSUE THREAD

**Issue by ctschach** [snowdd1/homebridge-knx-de#46]
Wollte eine simple Lampe mit Dimmer anlegen und steuern:

`            "DeviceName": "Schlafzimmer",
            "Services": [
                {
                    "ServiceType": "Lightbulb",
                    "ServiceName": "Deckenlicht",
                    "Characteristics": [
                        {
                            "Type": "On",
                            "Set": [
                                "1/2/40"
                            ],
                            "Listen": [
                                "1/2/40"
                            ]
                        },
                        {
                            "Type": "Brightness",
                            "Set": [
                                "1/2/42"
                            ],
                            "Listen": [
                                "1/2/42"
                            ]
                        }
                    ]
                },`

So weit so gut - normales "ein- und ausschalten" geht problemlos. Will ich allerdings die Helligkeit regeln, so wird erst die Helligkeit auf dem KNX-Bus gesetzt und danach auch noch "On" auf "1", was dazu führt, dass der Dimmer auf 100% Helligkeit geht.

Ist das ein Probleme von HomeKit oder ein Fehler in der KNX Implementierung?

Mit ist klar, dass ich das mit einem eigenen Handler umbauen kann. Aber muss ich das? Oder ist das ein Bug?

**Comment by snowdd1** [comment]
Das ist aus unserer Sicht ein Apple Bug. Da gibt es im englischen Repository schon eine längere Diskussion zu. Komme leider zur Zeit nicht dazu mich darum zu kümmern - aber es hat schon mal einer einen Handler programmiert

**Comment by ctschach** [comment]
Danke, habe ich gesehen...dann schließe das Issue hier, werde es weiter auf der englischen Seite verfolgen...

**Comment by snowdd1** [comment]
https://github.com/snowdd1/homebridge-knx/issues/47
