### ISSUE TITLE
Service ändern

### ISSUE THREAD

**Issue by kodibrain** [snowdd1/homebridge-knx-de#47]
Hi,
cool dass es hier etwas auf deutsch gibt :) da kann man sich vielleicht besser erklären.
ich habe mir einen Lecksensor an den Raspi via gpio angeschlossen.
Diesen wollte ich nun in die Homebridge einbinden, finde aber kein plugin dafür außer dieses https://github.com/pdemarco925/homebridge-doorsensor welches für ein Türkontakt ist. Kann ich den Service dieses plugins ändern? Wenn ja wie?

**Comment by snowdd1** [comment]
Hallo @kodibrain 
eigentlich machen wir ja hier nur KNX mit homebridge, aber ich will mal nicht so sein...

In Zeile [29](https://github.com/pdemarco925/homebridge-doorsensor/blob/master/index.js#L29) ist der Service als "ContactSensor" kreiert. Außerdem nutzt er die Eigenschaft "CurrentDoorState" in Zeile [14](https://github.com/pdemarco925/homebridge-doorsensor/blob/master/index.js#L14). In Zeile [43](https://github.com/pdemarco925/homebridge-doorsensor/blob/master/index.js#L43) ändert er den Contact-Status über den Typen des Service.

Mindestens diese (mehr habe ich jetzt nicht gefunden) müssten angepasst werden, um den ServiceType erfolgreich zu ändern. 

Viel Glück!
