### ISSUE TITLE
MDT Jalousie Aktor

### ISSUE THREAD

**Issue by cvuzem** [snowdd1/homebridge-knx-de#48]
Hallo,

ich bekomme es nicht hin wie beschrieben meine Jalousieaktoren von MDT mittels homebridge zu verbinden. Ich habe normale Rolladen, wie folgt in der ETS konfiguriert und funktionieren auf dem G1 und auf meiner Visu super.......:
![image](https://user-images.githubusercontent.com/37661043/38072284-dcf856dc-3325-11e8-810c-2ece105e8dc4.png)

Ich verstehe nicht welche Adresse wohin gehört.....Target, Position, Shutter usw.....

Wäre euch sehr dankbar...

**Comment by snowdd1** [comment]
```json
"Services": [{
	"ServiceType": "WindowCovering",
	"Handler": "GiraJalousieActuator",
	"ServiceName": "Rolling Shutter",
	"Characteristics": [{
		"Type": "TargetPosition",
		"Set": "1/3/13",
		"Listen": "1/3/13",
		"DPT": "DPT5.001"
	},
	{
		"Type": "CurrentPosition",
		"Set": "1/3/13",
		"Listen": "1/3/16"
	},
	{
		"Type": "PositionState"
	}],
	"KNXObjects": [{
		"Type": "ShutterMove",
		"Listen": "1/3/11",
		"DPT": "DPT1"
	}],
	"KNX-ReadRequests": ["1/3/16", "1/3/13"],
	"LocalConstants": {"TimeOutSecs": 60}
}]
```

Ich hoffe das hilft.
Ansonsten: https://github.com/snowdd1/homebridge-knx-de/wiki/Handler:-GiraJalousieActuator

**Comment by cvuzem** [comment]
Vielen Dank! Läuft endlich.....
Wisst ihr warum Alexa Jalousien als Lampen anzeigt und ob ich das irgendwie anpassen kann?
