### ISSUE TITLE
WindowCovering Problem

### ISSUE THREAD

**Issue by furiaceka87** [snowdd1/homebridge-knx-de#51]
Hi,
I've just set up Homebridge-knx and everything is working good talking about lightbulb, when I tried to configure the WindowCovering I found some issue.
here below my configuration:

> {
> "ServiceType": "WindowCovering",
> "Handler": "GiraJalousieActuator",
> "ServiceName": "Office blinds",
> "Characteristics": [
> {
> "Type": "TargetPosition",
> "Set": [
> "1/1/5R"
> ],
> "DPT": "DPT1"
> },
> {
> "Type": "CurrentPosition",
> "Listen": [
> "1/4/5R"
> ]
> },
> {
> "Type": "PositionState"
> }
> ]
> }

I think that the problem is that in my KNX configuration the commands sent to windowcovering are BOOLEAN "On" or "Off" as you can see on the attached image:
<img width="1278" alt="41432047-2026ca52-7015-11e8-80e5-3e4d68938b8c" src="https://user-images.githubusercontent.com/40276630/41465795-e5892aa8-709f-11e8-877c-217a0081c17e.png">

When I sent command by homekit I have percentage command to open and close instead that boolean commands:
<img width="1276" alt="41432092-41753dec-7015-11e8-9dfb-0435a0612037" src="https://user-images.githubusercontent.com/40276630/41465807-f4338e18-709f-11e8-902e-483f80c1b599.png">

and nothing happened...

Do you have any suggestion?

**Comment by ctschach** [comment]
You might need to create a custom handler or change any of the existing ones in order to match your Blind actors. 

Have a look at my very stupid handler as my blinds do not support positioning, just up and down:

https://github.com/snowdd1/homebridge-knx/blob/master/lib/addins/BJWavelineWindow.js

**Comment by furiaceka87** [comment]
Solved by enabling in ETS the percentage in another address. 

Thanks
