### ISSUE TITLE
Init Funktion für custom Handlers...

### ISSUE THREAD

**Issue by ctschach** [snowdd1/homebridge-knx-de#52]
Hi,

wie wäre es mit einer optionalen, zusätzlichen Funktion für die Custom Handlers - sowas wie

onHKInit()

welche direkt nach dem anlegen des Services mit seinen Characteristics aufgerufen wird.

Hintergrund ist, dass ich z.B. eine Characteristic wie "SetDuration" mittels einer lokalen Konstante aus der Config auf einen definierten Init-Wert setzen will. Solche Werte habe ich nicht auf dem KNX-Bus und will sie aber auch nicht uninitialisiert lassen.

In dem "constructor" kann ich es ja noch nicht aufrufen, da hier das Gerät noch nicht vollständig initialisiert ist. Helfen tue ich mir im Moment damit, dass ich beim ersten durchlauf von onKNXValueChange bzw. onHKValueChange meine Werte initialisiere, aber das ist nicht wirklich schön, da hier ja erst bei einer Interaktion der Wert gesetzt wird.

Vermutlich müsste man das irgendwo in der knxdevice nach dem "new ServiceKNX" machen, allerdings ist es mir noch nicht gelungen, hier eine Funktion aus dem CustomServiceAPI aufzurufen.

**Comment by ctschach** [comment]
Okay, habe das hinbekommen und in meinem Fork entsprechend eingebaut...

**Comment by snowdd1** [comment]
Hi @ctschach,
hast Du Lust aus Deinen Verbesserungen Pull requests zu machen?
Gruß
Raoul

**Comment by ctschach** [comment]
Du meinst nur das mit der init-function bei den custom handlern oder alle Änderungen?

**Comment by snowdd1** [comment]
Am besten natürlich alle :-)
Ich muss noch verstehen an welchen Stellen du das Grundprogramm verändern müsstest und wo das „Handler“ Konzept ausreichend war.

**Comment by snowdd1** [comment]
Hallo Carsten,
ich war mal so frei mir einen Teil des init-Codes zu kopieren. Ich habe ihn allerdings nicht ganz wörtlich übernommen:
Es wird drei hooks geben:
* `onServiceInit()` -- entspricht Deinem onHKInit()
* `onOrphanedDevice()` -- wird für alle Handler aufgerufen, deren Elternelement (Device) nicht zur aktuellen knx_config.json passt. Gedacht dafür, dass sich verwaiste Geräte später selbst entfernen können, was das im Handler entsprechend vorgesehen ist
* `onHomeKitReady()` -- wird für alle Handler aufgerufen, sobald **alle** Geräte fertig initialisiert sind. Somit sind ab diesem Moment auch Zugriffe auf andere Devices oder Services möglich.

Implementiert ist bisher nur der erste im Branch handlerInitEvent.

**Comment by snowdd1** [comment]
Mist, Gedankenfehler. Das mit den OrphanedDevices funktioniert nicht, weil die ja gerade keinen Eintrag in der knx_config.json mehr haben und damit auch keine Handler-Configuration. Bleiben noch zwei...


Dies sind in dem Branch jetzt drin.

**Comment by snowdd1** [comment]
Brauchtest Du für Elgato noch weitere Anpassungen, außerhalb der Handler? Irgendwo müssen ja noch die eve* Typen importiert werden, oder?

**Comment by ctschach** [comment]
Totgesagte leben länger. Bin gerade mal wieder dabei, alles auf die aktuelle Version zu bringen und es in den aktuellen branch einzupflegen.

Hattest Du "Dein "onServiceInit()" eigentlich jemals irgendwo eingebaut? Dann ihn in dem normalen branch nicht finden....

**Comment by snowdd1** [comment]
https://github.com/snowdd1/homebridge-knx/blob/handlerInitEvent/CHANGELOG.md

**Comment by snowdd1** [comment]
leider nie getestet - keine Zeit mehr gehabt

**Comment by snowdd1** [comment]
ist ein eigener branch

**Comment by ctschach** [comment]
Okay..danke....bin dabei, meinen fork auf den neusten Stand zu bringen....

**Comment by snowdd1** [comment]
Hi Carsten, habe endlich den den InitEvent branch gemerged. 
https://github.com/snowdd1/homebridge-knx/blob/master/CHANGELOG.md#0321

**Comment by ctschach** [comment]
Cool...ich habe das ganze mit der Eve History auch nochmal neu aufgebaut. Werde mal irgendwann einen Pull Request machen. Läuft eigentlich sehr zuverlässig....

Jetzt muss ich nur erstmal wieder Github verstehen, wie ich Deine Version neue Version mit meiner Merge.

**Comment by snowdd1** [comment]
Das ist für mich auch immer wieder eine Herausforderung. Wenn man nur alle paar Monate mal damit arbeitet, ist das eben kein eingeschliffener Prozess...
Magst Du Deine Änderunge nicht mal als Pull-requests in den Master hier zurückführen? Ich kann Dich auch zum Mitglied (collaborateur) machen... Soviel wie Du schon beigetragen hsat....
