### ISSUE TITLE
Aktoren Schalten beim Start von Homebridge

### ISSUE THREAD

**Issue by cvuzem** [snowdd1/homebridge-knx-de#55]
Hallo,

jedesmal wenn ich die Homebridge neu starte gehen alle Lampen aus und die Jalousien bewegen sich kurz runter und anschließend wieder hoch.

Hat jemand eine Idee wie ich das verhindern kann. Eigentlich sollte die Homebridge doch nur die Gruppenadressen lesen und nix senden?

**Comment by snowdd1** [comment]
Es soll Geräte geben die komisch auf Lese-Telegramme und die Antworten darauf reagieren. Meine tun das nicht. Hast Du noch andere Server mitlaufen, HomeServer, node-red, etc?

**Comment by cvuzem** [comment]
Hallo, ich habe es endlich herausgefunden. Es ist ein Binäreingang welcher beim Start abgerufen wird. Und es sind genau die Autoren welche schalten sollen wenn meine Alarmanlage Einbruch meldet....sprich den Binäreingang schaltet....
