### ISSUE TITLE
Gleichzeitiges schließen/öffnen von 2 Rollläden geht nicht

### ISSUE THREAD

**Issue by CyberChris79** [snowdd1/homebridge-knx-de#58]
Hallo,

vor ein paar Wochen lief noch alles ohne Probleme. Ich habe nichts geändert.
Irgendwann hab ich festgestellt, das immer ein Rollladen von den beiden den Status schließen/öffnen in der Homebridge anzeigt und nichts mehr macht, der andere funktioniert.
Es spielt auch keine Rolle welcher, denn an einem Tag macht er im Kinderzimmer Probleme und am anderen im Schlafzimmer.

Ich benutze die knxd version 0.14 und habe es über die knxd.conf und die knxd.ini probiert.
IWenn ich ein Rollladen nach dem anderen schließe/öffne, dann funktioniert es einwandfre, aber ich benutze Apple HomeKit Automatisation um die Rollläden im Kinderzimmer und Schlafzimmer zu schließen/öffnen undzwar zu einer bestimmten Uhrzeit.

Meine KNXD Optionen sehen so aus: `KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -c -b ipt:192.168.178.39"`
Ich benutze einen ABB IPR/S 3.1.1 IP-Router und steure die Geräte über Apple HomeKit und der Homebridge mit homebridge-knx.

Meine knx_config sieht so aus
`
{
"DeviceName": "Rollladen Kinderzimmer",
"Services": [
{
"ServiceType": "WindowCovering",
"Handler": "WindowCoveringTilt",
"ServiceName": "Rollladen Elias",
"Characteristics": [
{
"Type": "TargetPosition",
"Set": [
"1/1/150"
],
"Listen": [
"1/1/152"
],
"DPT": "DPT5"
},
{
"Type": "CurrentPosition",
"Listen": [
"1/1/152"
],
"DPT": "DPT5"
},
{
"Type": "PositionState"
},
{
"Type": "TargetHorizontalTiltAngle",
"Set": [
"1/1/150"
],
"Listen": [
"1/1/152"
],
"DPT": "DPT5"
},
{
"Type": "CurrentHorizontalTiltAngle",
"Listen": [
"1/1/152"
],
"DPT": "DPT5"
}
],
"KNXObjects": [
{
"Type": "ShutterMove",
"Listen": "1/1/152",
"DPT": "DPT1"
}
],
"KNXReadRequests": [
"1/1/152",
"1/1/153"
],
"LocalConstants": {
"ninetyDegRotation": "false"
},
"subtype": "SUB_9f575163-031d-4210-b77d-955aa7a82d30"
}
],
"UUID": "7e02224c-b3a9-4461-b932-713c494845f8"
}
`

Danke im Voraus

Christian

**Comment by snowdd1** [comment]
Hallo Christian,
falls das noch aktuell ist: Wahrscheinlich ist die Telegramrate für den Router zu hoch. knxd kann die irgendwie begrenzen, ich glaube es gibt einen "delay" Schalter.

**Comment by CyberChris79** [comment]
> 
> 
> Hallo Christian,
> falls das noch aktuell ist: Wahrscheinlich ist die Telegramrate für den Router zu hoch. knxd kann die irgendwie begrenzen, ich glaube es gibt einen "delay" Schalter.

Hallo Raoul,
vielen Dank für deine Nachricht.
Das Problem wurde durch Änderungen von Jalousie auf Gira Rolladen behoben.
Auch habe ich das Problem mit den Lamellen nicht mehr, da es diese bei den Rolladen natürlich nicht gibt.
Davor hatte ich die Rolläden mit dem Jalousie Programm in der Config gehabt.

LG
Christian
