### ISSUE TITLE
GarageDoorOpenerAdvanced keine "Geöffnet" Rückmeldung.

### ISSUE THREAD

**Issue by ghost** [snowdd1/homebridge-knx-de#59]
Hallo Raoul,

erst einmal, dir und allen anderen Entwicklern hier einen herzlichen Dank für eure Mühe und Arbeit.

Seit einigen Monaten schlage ich mich mit der Homebridge und dem KNX rum.
Viele Dinge laufen super einige noch nicht wirklich rund aber doch akzeptabel, was wahrscheinlich auf mein nicht wirklich vorhandenes Verständnis für eure Arbeit zurückzuführen ist.

Im Moment versuche ich mein Garagentor ans Laufen zu bekommen.

Via Bus ist alles schick und zugegebenermaßen wäre wohl das Misc2000GarageDoorOpener Plugin vollkommen zutreffend für meine Bedürfnisse. Mich stört dabei aber, dass der Status geschlossen angezeigt wird, wenn das Tor schon ein wenig geöffnet ist.

Deshalb versuche ich dein Plugin "GarageDoorOpenerAdvanced" einzubinden.

Ich habe ein Tor, dass über eine Eintaster- Bedienung, sprich Up/Stop/Down funktioniert. Vor 14 Tagen habe ich noch 2 Reedkontakte montiert, für die Endlagen. Das Tor wird über den Bus mit einem Aktor und Treppenlichtfunktion gesteuert. Beide Sensoren senden eine 1 für Kontakt geschlossen und 0 bei offen (DPT1).

GA Taster 5/0/0
GA Sensor Geschlossen 5/0/2
GA Sensor Geöffnet 5/0/1

Alles, was ich bisher ausprobiert habe, funktionierte nur mäßig. Jedoch wurde bei allen Versuchen das Tor nie automatisch auf "Geöffnet" gestellt. 
Die jetzige Konfiguration zeigt zuverlässig geschlossen an. Wenn das Tor geöffnet wird, passt danach auch. In der "Geöffnet" Lage wird der Status aber nicht geändert. D. h. "wird geöffnet" bleibt immer stehen. Wird jetzt ein weiters Mal die Taste im HK aktiviert, bewegt sich das Tor ca. 1 Sek ( abhängig von der "pulseLength") nach unten und zeigt "Schließen" an. Ein weiterer Tastendruck bringt wieder das "Wird geöffnet", dann auch mit der Meldung aus der Mitteilungszentrale. Mit viel Glück fährt das Tor nach öfterem Auf/Zu auch über die ersten Zentimeter hinaus und schließt das Tor.

Was mir wichtig ist, ist die Anzeige Tor "Geschlossen", ganz "Geöffnet" sowie, dass bei Tastendruck eine Richung durchgefahren wird und nicht das Tor stehen bleibt oder die Fahrt nach 1 Sek. umkehrt.

Hast du eine Idee wie ich das gelöst bekomme. Ggf. mache ich ja auch etwas grundlegend falsch.

Lieben Dank und allen schöne Ostertage

Ralf

```
{
            "DeviceName": "Garagentor",
            "Services": [
                {
                    "ServiceType": "GarageDoorOpener",
                    "Handler": "GarageDoorOpenerAdvanced",
                    "ServiceName": "Garagentor",
                    "Characteristics": [
                        {
                            "Type": "CurrentDoorState"
                        },
                        {
                            "Type": "TargetDoorState"
                        }
                    ],
                    "KNXObjects": [
                        {
                            "Type": "KNXPulseMove",
                            "Listen": "5/0/0",
                            "Set": "5/0/0",
                            "DPT": "DPT1"
                        },
                        {
                            "Type": "KNXDoorClosed",
                            "Listen": "5/0/2",
                            "DPT": "DPT1"
                        },
                        {
                            "Type": "KNXDoorOpened",
                            "Listen": "5/0/1",
                            "Set": "5/0/1",
                            "DPT": "DPT1"
                        }
                    ],
                    "KNXReadRequests": [
                        "5/0/1",
                        "5/0/2"
                    ],
                    "LocalConstants": {
                        "simulateDoorContactMode": "off",
                        "doorContactPresent": "both",
                        "staircaseFunc": false,
                        "separatePulseUpDown": false,
                        "sensorOn": 1,
                        "pulseLength": 400,
                        "doorRunTime": 20500
                    }
               }
            ]
        },
```

**Comment by snowdd1** [comment]
Pinging Christof @giase82 and Paul @c-o-m-m-a-n-d-e-r  die haben das geschrieben bzw. angepasst.

**Comment by giase82** [comment]
Servus!

Ich denke eigentlich, das sollte gelöst sein. Das Problem war glaube ich, das KNXDoorClosed in der Konfiguration anders hieß als im code des Plugins. Was hast du für eine Version @RABUE ?

//Christof

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Korrekt, eigentlich war das nur ein Typo.

Ich glaube aber zu verstehen was du meinst. Mein Leidensdruck war aber noch nicht hoch genug das anzugehen 😅 ich nutz primär den Homeserver für die Visu deshalb

**Comment by ghost** [comment]
Moin,
Danke für die Antworten.
Das Problem habt sich erledigt.
Ich habe auf den Misc2000GarageDoorOpener gewechselt.

Trotzdem Danke für Eure Mühe.
Ralf
