### ISSUE TITLE
alle Geräte in EVE verschwunden

### ISSUE THREAD

**Issue by Puki5000** [snowdd1/homebridge-knx-de#6]
ich habe eben eine neue config.json erstellt (das mache ich schon den ganzen Vormittag, Raum für Raum) -> Homebridge neu gestartet -> EVE hat keine Geräte mehr (außer der Homebridge selbst).

Alle Räume meiner Konfiguration sind in EVE noch da (aber nur, wen ich auf Einstellungen/Räume gehe).

Reset iPhone -> kein Erfolg

Verwenden der vorherigen config.json -> kein Erfolg

Und ja: ich hab sie auf jsonlint.com/ gecheckt ;o)

Irgendwelche Ideen? Ich möchte nicht schon wieder bei Null anfangen...

Grüße & frohe Ostern / dicke Eier!

**Comment by Puki5000** [comment]
Ok, ok...

Ich BIN in den 100 accessories-Fehler gelaufen _zerknirscht schau_

ABER: ist es denn sooo abwegig, dass ein normales Einfamilienhaus mehr als 100 accessories hat?

Denn wenn ich in unserem speziellen Fall (KNX) in einem Raum z.B. mehrere Leuchten habe (was wohl der Regelfall sein dürfte), dann MUSS ich diese, wenn ich sie z.B. in EVE nicht nur als "anonyme Lampe" mit "Strom AUS EIN" sehen will, als separates accessory anlegen. Nur dann habe ich auch den dort vergebenen Namen.

Oder mache ich einen Denkfehler?

Oder kommt es in Apples Welt nicht vor, dass ein accessory mehr als eine gleichartige Funktion besitzt?

**Comment by snowdd1** [comment]
Hallo @Puki5000 

> ABER: ist es denn sooo abwegig, dass ein normales Einfamilienhaus mehr als 100 accessories hat?

Aus Apples Sicht schon, denn die haben ja nicht an die **smart homes** gedacht wie wir sie haben, sondern an den Nachrüstmarkt mit Philips Hue, Elgato Door & Window etc., und da sind 100 Accessories **pro Bridge** eigentlich nicht hinzubekommen.
Es gibt eine laufende Diskussion, bzw. immer wieder Diskussionen, ob man nicht einfach mehrere Bridges aus homebridge heraus erzeugen könnte - bisher wollte aber niemand so viel Arbeit da reinstecken, weil es den workaround mit mehreren Services pro accessory gibt.

Die Anzeige in Elgato EVE ist tatsächlich blöd - in der "Auf einen Blick" und der Raumdarstellung wird der Dienst-Name nicht mit angezeigt, sobald es mehrere Dienste in einem Gerät gibt - sonst schon, das erscheint widersinnig. In der Typendarstellung (Alle "Strom") tauchen die Namen dann wieder richtig auf. Das ist blöd. Vielleicht ändert da Elgato ja auch noch etwas dran, aber eigentlich wollen die ja ihre Hardware verkaufen.

Wünsche frohe Ostern gehabt zu haben!
Raoul

**Comment by Puki5000** [comment]
Hallo Raoul,

vielen Danke für deine Infos. Die mehreren Instanzen Homebridge - das war auch eine Idee, die mir kam. Ist aber eher unelegant ;o)

Mir ist übrigens aufgefallen, dass EVE nur **einen** Namen anzeigt, wenn der Name von accessory und Service in der config.json identisch ist...

Grüße
Puki
