### ISSUE TITLE
100 Geräte / Config Aufbau

### ISSUE THREAD

**Issue by baumph** [snowdd1/homebridge-knx-de#62]
Hallo zusammen!
Ich bin bei meiner Homebridge mittlerweile bei 85 Geräten angekommen und habe auch noch einige die ich programmieren will. Da aber bekannterweise die Homebridge "nur" 99 verträgt habe ich gestern versucht die Geräte unter einem Device zu bündeln mit unterschiedlichen ServiceTypes. Das hat auch soweit geklappt, meine 3 ServiceTypes wurden in der Apple Home App unter einem Device angezeigt. Und die Bridge wurde auch mit 86 Geräten erkannt.
Das Problem ist jetzt, dass ich die 3 Geräte aber gerne als einzelne Kacheln in der Home App sehen will. Diese Option gibt es auch, aber danach ist leider meine Accessory Anzahl auf 89 hoch gegangen...
Was ist für das 100 Geräte Problem ausschlaggebend? Die Anzahl der Devices in der Config, oder die Anzahl, die die Home App anzeigt?
Und ist es möglich, dass ich die ServiceTypes einzeln anzeigen kann? 

Ich hoffe, dass mir jemand helfen kann.

**Comment by giase82** [comment]
Servus!

Wäre wahrscheinlich einfacher, wenn du einfach eine weitere Instanz laufen lässt.

//giase
