### ISSUE TITLE
Handler: SimpleGarageDoor

### ISSUE THREAD

**Issue by CyberChris79** [snowdd1/homebridge-knx-de#65]
Hello,

is ist possible to set an timeout like an relay or an switch to this handler?
I want to use this handler to open and close my garage door through a security component, which use an relay to send an signal to the door.
Now if iam using this handler, the relay is always on and does not switch off again.
I have to cut the power.

Or is the handler: relay or switch the better solution for me?
I like the garage handler, because of the icon in Apple HomeKit :)

Thank you in Advance
Chris

**Comment by snowdd1** [comment]
Hi Chris, I have it split: my Gira homeserver sends the "off" after it senses an "on" telegram, and the apple homekit integration does the rest.

**Comment by CyberChris79** [comment]
Hallo Raoul.
vielen Dank für deine schnelle Antwort.
Ich hatte ganz vergessen, das ich dir auch auf deutsch schreiben kann.
Am besten erkläre ich dir das Problem nochmals.

In meiner Garage befindet sich ein Garagen Antrieb von Teckentrup CarTeck 220.2.

Dieser wird momentan über 2 verschiedene Arten gesteuert.
1. Über 2 Taster und zwar in der Garage und im Haus. Hier wird einfach über ein Relay geöffnet/gestoppt/geschlossen.
2. Über eine Telenot Alarmanlage, die auch an das Relay über einen Ausgang angeschlossen ist und per App den Befehl sendet.

Vor kurzem habe ich ein KNX IP 400 Modul in die Alarmanlage eingebaut, damit ich Türen, Fenster, Bewegungsmelder, die sowieso schon über die Telenot angeschlossen sind, auch über HomeKit sehen kann. Dies funktioniert einwandfrei. Ich kann die Bewegungsmelder im unscharfen Zustand sogar als Präsenzmelder für das Licht einsetzen.
Das Garagentor konnte ich auch einbinden. Das funktioniert wie die Fenster und Türen.

Nun komm ich zu meinem eigentlichen Problem.
Ich möchte den Zustand, das Öffnen und das Schließen über ein Schalter im HomeKit steuern.
Hier komme ich nicht weiter. Die Garage lässt sich über den Impuls öffnen, das geöffnete Garagentor wird auch als geöffnet angezeigt. Wenn ich das Tor nun schließe wird es auch wieder als geschlossen angezeigt, aber eben nur einmal. Danach wird nicht mehr aktualisiert bzw. es wird immer "wird geöffnet" oder "wird geschlossen" angezeigt. Wenn ich nun HomeKit beende und neu öffne, wird der alte Zustand wieder angezeigt.

Ich habe schon alle möglichen Parameter in dem Garagendoor Handler ausprobiert.
Die Telenot nutzt eine Gruppenadresse für ein oder aus, d.h. ich habe nur einen Sensor an der Garage. Dieser Zustand wird auch problemlos in der ETS aktualisiert.
Im Homebridge Debug Modus, kann ich erkennen das der Status sich von 0 auf 1 ändert. Ich kann mir aber vorstellen das es dann von 2 auf 3 wechselt. Ich benötige jedoch keine Stopp oder Fahrt Rückmeldung, sondern nur 1 oder 0. Der Torantrieb wird auch nicht zusätzlich über einen KNX Aktor gesteuert.

Kannst du mit da bitte weiterhelfen?

Vielen Dank im Voraus

LG
Christian

**Comment by snowdd1** [comment]
Probier mal die neue Version aus - hat mich in den Fingern gejuckt. 
Hat jetzt zwei neue Parameter: ResetOpenDoorContactTime und ResetCloseDoorContactTime, insgesamt also:

 * CloseDoor with Set and Listen (DPT1: 1 starts move, 0 is ignored)
 * OpenDoor with Set and Listen (DPT1: 1 starts move, 0 is ignored)
 * TravelTime as LocalConstant ==> in Seconds
 * ResetOpenDoorContactTime as LocalConstant ==> in MilliSecs, so 500 is half a second!
 * ResetCloseDoorContactTime as LocalConstant ==> in MilliSecs

Wichtig ist in Deinem Fall dass Du die Fahrtzeit in Sekunden eingibst. In Meinem Fall fährt das Tor 18 Sekunden, also habe ich mal 20 hinterlegt, dann ist es auf jeden Fall zu. Blockaden etc. kann das Tor eh' nicht zurückmelden. Nach 20 Sekunden wird das Tor vom Add-In als geschlossen gemeldet, und Homekit ändert das Symbol - Anlog beim Öffnen.

Falls Du zwei Zustände auf der gleichen DPT verwendest, dann müsstest Du den Handler allerdings noch umprogrammieren, oder Dich am deutlich komplexeren GarageDoorAdvanced probieren, der ist allerdings nicht von mir, sondern von Christoph (@giase82)

**Comment by snowdd1** [comment]
Nachdem ich Deinen Text nochmal gelesen habe, komme ich immer mehr zu dem Ergebnis dass der GarageDoorAdvanced handler der richtige für Dich ist. Diese Auf/Stop/Zu/Stop/Auf-Logic über ein Relais-Kontakt (und eben nicht über zwei wie bei mir) ist genau das, was Christoph damals abbilden wollte.

**Comment by CyberChris79** [comment]
Hallo Raoul,

vielen Dank für deine Rückmeldung.
Ich habe diesen Handler bereits auch ausprobiert und auch hier hatte ich das gleiche Problem.

Mich interessiert ja nur Auf und Zu. Mehr will ich eigentlich nicht.
D.h. Ich benötige einen Impuls zum Öffnen und zum Schließen und nach dieser Aktion soll der Status sich jeweils ändern.

Geht das nicht mit deinem Handler?
Danke dir

Gruß
Christian

**Comment by CyberChris79** [comment]
Ich habe das Update jetzt installiert.
Der Zustand wird jeweils umgekehrt angezeigt. D.h. wenn die Garage geöffnet ist, wird der Zustand als geschlossen angezeigt.

**Comment by CyberChris79** [comment]
Hallo Raoul,

Ich habe mael einen ServiceTyp ContactSensor für die Garage angelegt und dieser zeigt den Wert offen oder geschlossen richtig an.
Ich bräuchte quasi nur einen Handler, der die Garage per Impuls öffnet und schließt und den Status offen oder zu anzeigt damit ich nur einen Button in Homekit habe. Damit kann ich dann beides machen und es sollte als Garagen Symbol angezeigt werden.
Leider bin ich im programmieren nicht so Fit.
Kannst du mir da weiter helfen?

Danke dir

LG
Christian

**Comment by giase82** [comment]
Hi zusammen,

Falls ich was hier was zu GarageDoorOpenerAdvanced helfen kann, sagt bitte Bescheid. Bin mir aufgrund dieser Diskussion nicht ganz sicher, ob das noch relevant ist.

//Christof

**Comment by CyberChris79** [comment]
Hallo Christof,

 

vielen Dank für deine Rückmeldung.

Ja, das ist noch relevant, da ich leider nicht weiter komme.

 

Ich benötige einen Garagentaster im HomeKit der einfach nur einen kurzen Impuls zum Öffnen, Stoppen und Schließen sendet.

Dieser muss nicht unbedingt Öffnen oder Schließen währen der Fahrt anzeigen. Es reicht wenn er anzeigt ob mein Sensor nach dem Impuls immer noch geöffnet oder geschlossen ist.

 

Ich hoffe ich konnte das so erklären, dass man es versteht 😊

 

Viele Grüße

Christian

 

Von: giase82 <notifications@github.com> 
Gesendet: Freitag, 22. Mai 2020 13:45
An: snowdd1/homebridge-knx-de <homebridge-knx-de@noreply.github.com>
Cc: CyberChris79 < *ADDRESS REMOVED* >; Author <author@noreply.github.com>
Betreff: Re: [snowdd1/homebridge-knx-de] Handler: SimpleGarageDoor (#65)

 

Hi zusammen,

Falls ich was hier was zu GarageDoorOpenerAdvanced helfen kann, sagt bitte Bescheid. Bin mir aufgrund dieser Diskussion nicht ganz sicher, ob das noch relevant ist.

//Christof

**Comment by giase82** [comment]
Hi Christian,

Ich denke, dass du den GarageDoorOpenerAdvanced so Konfigurieren kannst, dass das passt. Hast du Sensoren für offen/geschlossen (einen oder beides)? Wie lange muss der Impuls sein? Ich kann dir dann mal eine config vorschlagen.

//Christof

**Comment by CyberChris79** [comment]
Hallo Christof,

 

vielen Dank für deine Rückmeldung.

 

ich habe einen Magnetkontakt über die Telenot Alarmanlage. Diese habe ich über KNX bereits angeschlossen.

Wenn also die Garage zu ist, dann ist der Kontakt geschlossen und sobald kein Kontakt zum Magneten ist, ist die Garage offen.

Also habe ich nur einen Sensor.

Der Impuls muss nur ganz kurz sein. Ich kann die Garage auch über einen analogen Taster betätigen..

 

Vielen Dank im Voraus.

Christian

 

Von: giase82 <notifications@github.com> 
Gesendet: Freitag, 22. Mai 2020 16:40
An: snowdd1/homebridge-knx-de <homebridge-knx-de@noreply.github.com>
Cc: CyberChris79 <cyberchris79@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [snowdd1/homebridge-knx-de] Handler: SimpleGarageDoor (#65)

 

Hi Christian,

Ich denke, dass du den GarageDoorOpenerAdvanced so Konfigurieren kannst, dass das passt. Hast du Sensoren für offen/geschlossen (einen oder beides)? Wie lange muss der Impuls sein? Ich kann dir dann mal eine config vorschlagen.

//Christof

**Comment by CyberChris79** [comment]
Hallo Christof,

 

hast du meine letzte E-Mail bekommen?

 

Viele Grüße

Christian

 

Von: giase82 <notifications@github.com> 
Gesendet: Freitag, 22. Mai 2020 16:40
An: snowdd1/homebridge-knx-de <homebridge-knx-de@noreply.github.com>
Cc: CyberChris79 <cyberchris79@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [snowdd1/homebridge-knx-de] Handler: SimpleGarageDoor (#65)

 

Hi Christian,

Ich denke, dass du den GarageDoorOpenerAdvanced so Konfigurieren kannst, dass das passt. Hast du Sensoren für offen/geschlossen (einen oder beides)? Wie lange muss der Impuls sein? Ich kann dir dann mal eine config vorschlagen.

//Christof

**Comment by giase82** [comment]
Sorry, übersehen.

Der Handler kann auch einen geschlossen-Sensor simulieren. Hatte ich bei mir auch so. Ich denke deine config sollte so aussehen:

KNXPulseMove -> dein Impuls
KNXDoorClosed -> dein Sensor
doorRunTime -> einfach mal Laufzeit messen und in ms eintragen
pulseLength -> sollte mit 500ms in etwa passen

> 

        {
            "DeviceName": "Garagentor",
            "Services": [
                {
                    "ServiceType": "GarageDoorOpener",
                    "Handler": "GarageDoorOpenerAdvanced",
                    "ServiceName": "Garagentor",
                    "Characteristics": [
                        {
                            "Type": "CurrentDoorState"
                        },
                        {
                            "Type": "TargetDoorState"
                        }
                    ],
                    "KNXObjects": [
                        {
                            "Type": "KNXPulseMove",
                            "Set": "2/3/0",
                            "Listen": "2/3/0",
                            "DPT": "DPT1"
                        },
                        {
                            "Type": "KNXDoorClosed",
                            "Listen": "2/3/2",
                            "DPT": "DPT1"
                        }
                    ],
                    "KNXReadRequests": [
                        "2/3/2"
                    ],
                    "LocalConstants": {
                        "simulateDoorContactMode": "internal",
                        "doorContactPresent": "closed",
                        "staircaseFunc": false,
                        "separatePulseUpDown": false,
                        "sensorOn" : 1,
                        "pulseLength": 500, 
                        "doorRunTime": 18500
                    }
                }
            ]
        }

Hoffe das hilft!

//Christof

**Comment by CyberChris79** [comment]
Hallo Christof,

 

kein Problem, deswegen hatte ich mich ja nochmals gemeldet. Ich dachte schon das es untergegangen ist 😉

Vielen Dank für die Konfig.

 

Ich werde gleich mal die doorRunTime noch messen, dann die neue Konfig einspielen und ich gebe dir dann nochmals Bescheid.

 

Schönen Abend

 

Grüße

Christian

 

Von: giase82 <notifications@github.com> 
Gesendet: Dienstag, 26. Mai 2020 18:00
An: snowdd1/homebridge-knx-de <homebridge-knx-de@noreply.github.com>
Cc: CyberChris79 <cyberchris79@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [snowdd1/homebridge-knx-de] Handler: SimpleGarageDoor (#65)

 

Sorry, übersehen.

Der Handler kann auch einen geschlossen-Sensor simulieren. Hatte ich bei mir auch so. Ich denke deine config sollte so aussehen:

KNXPulseMove -> dein Impuls
KNXDoorClosed -> dein Sensor
doorRunTime -> einfach mal Laufzeit messen und in ms eintragen
pulseLength -> sollte mit 500ms in etwa passen

    {
 
        "DeviceName": "Garagentor",
 
        "Services": [
 
            {
 
                "ServiceType": "GarageDoorOpener",
 
                "Handler": "GarageDoorOpenerAdvanced",
 
                "ServiceName": "Garagentor",
 
                "Characteristics": [
 
                    {
 
                        "Type": "CurrentDoorState"
 
                    },
 
                    {
 
                        "Type": "TargetDoorState"
 
                    }
 
                ],
 
                "KNXObjects": [
 
                    {
 
                        "Type": "KNXPulseMove",
 
                        "Set": "2/3/0",
 
                        "Listen": "2/3/0",
 
                        "DPT": "DPT1"
 
                    },
 
                    {
 
                        "Type": "KNXDoorClosed",
 
                        "Listen": "2/3/2",
 
                        "DPT": "DPT1"
 
                    }
 
                ],
 
                "KNXReadRequests": [
 
                    "2/3/2"
 
                ],
 
                "LocalConstants": {
 
                    "simulateDoorContactMode": "internal",
 
                    "doorContactPresent": "closed",
 
                    "staircaseFunc": false,
 
                    "separatePulseUpDown": false,
 
                    "sensorOn" : 1,
 
                    "pulseLength": 500, 
 
                    "doorRunTime": 18500
 
                }
 
            }
 
        ]
 
    }
 

Hoffe das hilft!

//Christof

**Comment by CyberChris79** [comment]
Hallo Christof,

ich habe heute deine Konfiguration eingespielt und getestet. 

Leider passt diese nicht für meine Situation. 

Das Problem ist, dass ich die Garage von 2 Stellen aus bedienen kann. 
Einmal über einen analogen Taster im Haus bzw. in der Garage und über die Telenot App.
In beiden Fällen wird ein kurzer Impuls über ein Relay an den Motor gesendet. 
D.h. Öffnen/Stoppen/Schließen. 

Sobald ich über einen dieser Wege die Garage bediene, sehe ich über Telenot App ob die Garage geöffnet oder geschlossen ist, da ein Magnet den Sensor öffnet oder schließt. 

Nun habe ich ein KNX Modul in die Telenot eingebaut, damit ich die Garage auch über einen dritten Weg bedienen kann, und zwar über HomeKit. 

Wenn ich nun deine Konfiguration nehme und die Garage über die Telenot App oder den analogen Taster bediene, sollte der Status auch in HomeKit angezeigt werden und das passiert eben nicht. Das geht nur wenn die Garage über HomeKit bedient wird. Dies ist aber nicht jedesmal der Fall. Ich öffne diese auch mal über die Telenot App oder den Taster und das bekommt dann HomeKit nicht mit. 

Über den Handler ContactSensor jedoch wird es in HomeKit angezeigt, aber dort habe ich leider keinen Switch Button. 

Ich suche also nach einer Lösung, der den Status bei onChange an HomeKit weiter gibt, egal mit welcher der 3 Möglichkeiten ich die Garage bediene und zusätzlich sollte es möglich sein über diesen Button in HomeKit den Impuls zu senden. Ich benötige auch kein Öffnen oder Schließen, sonder nur geöffnet und geschlossen. 

Kannst du mir da weiter helfen?

Vielen Dank im Voraus 

Viele Grüße 
Christian

**Comment by CyberChris79** [comment]
Hallo Christof,

 

hast du meine letzte Nachricht erhalten?

Ich habe nun dein Handler auf das Minimum reduziert.

D.h. ich habe nun einen Switch für das Öffnen und Schließen und die Anzeige ob die Garage offen oder geschlossen ist, wird über KNX ausgelesen.

Nun ich aber noch das Problem, das dies wunderbar direkt über HomeKit funktioniert, aber wenn jetzt die Garage gechlossen ist und auch im HomeKit so angezeigt wird, ich per Siri erneut „Garagentor schließen“ sage, dann öffnet er mir die Garage wieder. Also das Script sendet immer den sendPulse() über Siri mit 1.

Wie kann ich das verhindern?

 

Hier ist der Code http://pastie.org/p/0IiNAGiBOV0PZexFf7T4w5

 

Danke dir im Voraus.

 

Gruß

Christian

 

 

Von: giase82 <notifications@github.com> 
Gesendet: Dienstag, 26. Mai 2020 18:00
An: snowdd1/homebridge-knx-de <homebridge-knx-de@noreply.github.com>
Cc: CyberChris79 <cyberchris79@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [snowdd1/homebridge-knx-de] Handler: SimpleGarageDoor (#65)

 

Sorry, übersehen.

Der Handler kann auch einen geschlossen-Sensor simulieren. Hatte ich bei mir auch so. Ich denke deine config sollte so aussehen:

KNXPulseMove -> dein Impuls
KNXDoorClosed -> dein Sensor
doorRunTime -> einfach mal Laufzeit messen und in ms eintragen
pulseLength -> sollte mit 500ms in etwa passen

    {
 
        "DeviceName": "Garagentor",
 
        "Services": [
 
            {
 
                "ServiceType": "GarageDoorOpener",
 
                "Handler": "GarageDoorOpenerAdvanced",
 
                "ServiceName": "Garagentor",
 
                "Characteristics": [
 
                    {
 
                        "Type": "CurrentDoorState"
 
                    },
 
                    {
 
                        "Type": "TargetDoorState"
 
                    }
 
                ],
 
                "KNXObjects": [
 
                    {
 
                        "Type": "KNXPulseMove",
 
                        "Set": "2/3/0",
 
                        "Listen": "2/3/0",
 
                        "DPT": "DPT1"
 
                    },
 
                    {
 
                        "Type": "KNXDoorClosed",
 
                        "Listen": "2/3/2",
 
                        "DPT": "DPT1"
 
                    }
 
                ],
 
                "KNXReadRequests": [
 
                    "2/3/2"
 
                ],
 
                "LocalConstants": {
 
                    "simulateDoorContactMode": "internal",
 
                    "doorContactPresent": "closed",
 
                    "staircaseFunc": false,
 
                    "separatePulseUpDown": false,
 
                    "sensorOn" : 1,
 
                    "pulseLength": 500, 
 
                    "doorRunTime": 18500
 
                }
 
            }
 
        ]
 
    }
 

Hoffe das hilft!

//Christof

**Comment by CyberChris79** [comment]
Hallo Christof,

 

ich habe es selber gelöst.

Danke dir

 

LG

Christian

 

Von: giase82 <notifications@github.com> 
Gesendet: Dienstag, 26. Mai 2020 18:00
An: snowdd1/homebridge-knx-de <homebridge-knx-de@noreply.github.com>
Cc: CyberChris79 <cyberchris79@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [snowdd1/homebridge-knx-de] Handler: SimpleGarageDoor (#65)

 

Sorry, übersehen.

Der Handler kann auch einen geschlossen-Sensor simulieren. Hatte ich bei mir auch so. Ich denke deine config sollte so aussehen:

KNXPulseMove -> dein Impuls
KNXDoorClosed -> dein Sensor
doorRunTime -> einfach mal Laufzeit messen und in ms eintragen
pulseLength -> sollte mit 500ms in etwa passen

    {
 
        "DeviceName": "Garagentor",
 
        "Services": [
 
            {
 
                "ServiceType": "GarageDoorOpener",
 
                "Handler": "GarageDoorOpenerAdvanced",
 
                "ServiceName": "Garagentor",
 
                "Characteristics": [
 
                    {
 
                        "Type": "CurrentDoorState"
 
                    },
 
                    {
 
                        "Type": "TargetDoorState"
 
                    }
 
                ],
 
                "KNXObjects": [
 
                    {
 
                        "Type": "KNXPulseMove",
 
                        "Set": "2/3/0",
 
                        "Listen": "2/3/0",
 
                        "DPT": "DPT1"
 
                    },
 
                    {
 
                        "Type": "KNXDoorClosed",
 
                        "Listen": "2/3/2",
 
                        "DPT": "DPT1"
 
                    }
 
                ],
 
                "KNXReadRequests": [
 
                    "2/3/2"
 
                ],
 
                "LocalConstants": {
 
                    "simulateDoorContactMode": "internal",
 
                    "doorContactPresent": "closed",
 
                    "staircaseFunc": false,
 
                    "separatePulseUpDown": false,
 
                    "sensorOn" : 1,
 
                    "pulseLength": 500, 
 
                    "doorRunTime": 18500
 
                }
 
            }
 
        ]
 
    }
 

Hoffe das hilft!

//Christof

**Comment by giase82** [comment]
Hi Christian,

Sorry, bin grade etwas unter Wasser.... Cool dass du's geschafft hast!

//Christof

**Comment by CyberChris79** [comment]
Hallo Christof,

 

danke für deine Rückmeldung.

Ich weiss eben nur nicht ob das so in Ordnung ist.

 

Vielleicht kannst dich nochmals melden wenn du mehr Zeit hast und dir den Handler mal anschauen.

 

LG

Christian

 

Von: giase82 <notifications@github.com> 
Gesendet: Donnerstag, 4. Juni 2020 17:18
An: snowdd1/homebridge-knx-de <homebridge-knx-de@noreply.github.com>
Cc: CyberChris79 <cyberchris79@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [snowdd1/homebridge-knx-de] Handler: SimpleGarageDoor (#65)

 

Hi Christian,

Sorry, bin grade etwas unter Wasser.... Cool dass du's geschafft hast!

//Christof
