### ISSUE TITLE
Alarmmeldung

### ISSUE THREAD

**Issue by Gorgmaster** [snowdd1/homebridge-knx-de#66]
Hallo zusammen,

ich suche nach einer Möglichkeit, eine Meldung auszugeben. Z.B. einen Regenalarm.
Ich habe meiner Frau eine Taste im Hauswirtschaftsraum angelegt, die sie betätigt, wenn die Wäsche draußen hängt. Fängt es an zu regnen blinken die LED's an verschiedenen Tastern im Haus. Es wäre doch recht smart, wenn es eine Möglichkeit gäbe, eine Meldung auszugeben. Ähnlich dem GarageDoorOpener, wenn das Garagentor geöffnet oder geschlossen wurde.

Ich habe bisher nichts finden können, was das abbildet. Gibt es da schon was?
Trigger wäre dann eine KNX-Adresse.

**Comment by snowdd1** [comment]
Du kannst es als Sensor anlegen, z.B. Service ContactSensor. Der meldet dann "wurde göffnet" oder "wurde geschlossen" je nach 1 oder 0 meldung auf der Adresse.

**Comment by Gorgmaster** [comment]
Ich nehme mal an, dass eine Änderung von "wurde geöffnet" oder "wurde geschlossen" ist nicht möglich?

**Comment by snowdd1** [comment]
Natürlich... nicht.

**Comment by Gorgmaster** [comment]
Tolle Wurst! Dann können wir denke ich hier zu machen.

**Comment by snowdd1** [comment]
Naja, kommt drauf an. Du kannst ja den Namen des Geräts anpassen. Wie wäre es mit "Die Schleuse des Himmels" (wurde geöffnet/wurde geschlossen)?
Apple hat halt für jeden (mitteilungsfähigen) Service einen "passenden" Text ausgesucht. Da der in 100 Sprachen auf dem Gerät gespeichert ist, ist das nicht so flexibel.

**Comment by Gorgmaster** [comment]
Das ist ne klasse Idee :)
