### ISSUE TITLE
LightSensor wird nicht im Status angezeigt

### ISSUE THREAD

**Issue by Gorgmaster** [snowdd1/homebridge-knx-de#67]
Habe bei mir einen LightSensor angelegt und die Außenhelligkeit damit verknüpft. Wird auch soweit angezeigt. Stellt man aber unter Einstellungen den Schalter auf "im Status anzeigen" ein, dann taucht die Information nicht im Status auf.

**Comment by snowdd1** [comment]
Stimmt, bei mir auch nicht. Favoriten geht.
Ich denke das ist ein Fehler dass man das Aussuchen kann. Bei Fenster "offen" tauchen die im Status auf, bei "Licht an" und bei "Wasserhahn offen" - Bei Helligkeit? Was sollte der "Auslöser" sein?

**Comment by Gorgmaster** [comment]
Naja, ich hab einen Temperatursensor angelegt. Den mit der Außentemperatur verknüpft und Status aktiviert. So wird immer die Außentemperatur angezeigt. So hatte ich mir das eigentlich mit der Helligkeit auch gedacht. Windgeschwindigkeit wollte ich auch noch, hab ich aber als Device auch nicht gefunden.
