### ISSUE TITLE
Homebridge findet meine KNX Geräte nicht

### ISSUE THREAD

**Issue by Olaf-Kueppers** [snowdd1/homebridge-knx-de#68]
Hallo

soweit ich es beurteilen kann, habe ich mich an alle Schritte gehalten, um die Installation von Homebridge, Homebidge-KNX und knxd erfolgreich abzuschliessen, aber leider sehe ich im UI keins meiner KNX-Devices (ich habe erstmal mit einem meiner Schalter anfangen wollen).
Nochmal kurz zu den (mir ersichtlichen) Fakten:

- Homebridge läuft, die Config-UI ist erreichbar, HomeKit auf meinem iPhone hat eine Verbindung herstellen können.
- Homebridge-KNX ist installiert (per GUI), und laut Log wird die Plattform auch geladen, allerdings sehe ich keinerlei Log-Einträge mit "[KNX] ... "
- knxd läuft, ich kann mit "knxtool groupswrite" Aktoren ein/ausschalten
- in der knx_config.json habe ich localhost, Port 6720 als knxd Angaben eingetragen
- 149535 4 -rwxrwxrwx  1 homebridge homebridge  736 Jun 22 11:34 knx_config.json

Wär klasse, wenn man mir helfen könnte, den (hoffentlich) einen Punkt rauszufinden, den ich vermutlich übersehen habe...?

Danke + Grüße
Olaf

**Comment by rw71** [comment]
Ich habe genau das gleiche Problem. Irgendwie fehlt die Verbindung zwischen **Homebridge Config UI X** und **Homebridge KNX**

**Comment by rw71** [comment]
Ich konnte das Problem lösen. KNX muss als platform in die Konfiguration von Homebridge eingetragen werden.
Eine Komplette Anleitung für die Installation von Homebridge für KNX habe ich [hier](https://www.wudernitz.at/wiki/doku.php?id=raspberry_pi:homebridge_mit_knx_auf_raspberry_pi) erstellt.

**Comment by snowdd1** [comment]
Duplikat zu https://github.com/snowdd1/homebridge-knx/issues/163 (english)
