### ISSUE TITLE
KNX-Szenen?

### ISSUE THREAD

**Issue by s1nn3r** [snowdd1/homebridge-knx-de#8]
Hallo,

wirklich ein super Plugin, das Schalten und Dimmen von Lampen funktioniert bereits.
Aber was ich wirklich brauchen könnte, wäre das Aktivieren von KNX-Szenen, dann könnte ich mir sehr viel Arbeit beim Anlagen von Devices sparen.
Falls Homekit keine Szenen unterstützt, könnte man vielleicht mit einem "virtuellen" Schalter tricksen?
Ich will eigentlich nur mit Siri schalten, nachdem ich auch einen Gira Homeserver betreibe, wäre mir die Visualisierung über Homekit nicht so wichtig.

Danke für die Hilfe.
Marc

**Comment by snowdd1** [comment]
Hallo Marc, 
Du kannst einen "Switch" benutzen (https://github.com/snowdd1/homebridge-knx#switch). HomeKit kann selber Szenen (zu konfigurieren z.B. in EVE ode Hesperus), allerdings funktionieren die natürlich immer nur wenn auch das i-Gerät dabei ist - Verwende daher auch selbst (noch) keine.

Wenn Du also einen DPT1-Szenenschalter brauchst ist der "Switch" genau der richtige. Siri hört dann auf "Schalte <Service-Name> an/aus"

Gruß
Raoul

**Comment by s1nn3r** [comment]
Hallo Raoul,

danke für Deine schnelle Antwort und sorry, dass ich nochmal nachhaken muss.
Bei KNX-Szenen muss ich ja die Szenennummer an eine allgemeingültige KNX-Szenen-Gruppenadresse senden, beim normalen Switch fehlt mir dieser Parameter aber doch, oder?

Grüße
Marc

**Comment by snowdd1** [comment]
Richtig, aber Du kannst es an den HS schicken (an eine eigene Adresse dafür) und der übernimmt das mapping dann.

**Comment by s1nn3r** [comment]
Ah, verstanden! Aufwändiger als ich gehofft hatte, aber eine mögliche Lösung.
Danke.
Ein Tool, was einen ETS-Export in eine config.json Datei für Dein Plugin umwandelt hast Du nicht zufällig schon selber gebastelt, oder?

**Comment by snowdd1** [comment]
Hallo @s1nn3r ,
für die neue Version 0.3 (derzeit beta) kannst Du kleine add-ins basteln, die quasi beliebigen code ausführen können (aber nicht sollen :smile: ) und daher für solche Automatisierungen wie geschaffen sind!

Ich verwende selbst keine KNX-Szenen, aber wenn Du die Anforderungen mal auflistest, kann ich gerne ein kleines Add-in zum Testen bereit stellen.

Und zu Deiner letzten Frage: so etwas hatte ich mal begonnen, und habe es wieder begraben, weil die Anforderungen an die Struktur der GAs extreme sind, und wohl niemend es (im privaten Umfeld zumindest) geschafft hat immer so konsequent zu sein.

**Comment by NederBelg** [comment]
I just installed the homebridge-knx. All seems to be working to the point where the connection has to be made to the gira homeserver. I think have the gateway settings correct. But may I forgot a detail. Do you have a list of settings on the gira homeserver gateway, so the homebridge can communicate with it?
